# -*- coding: utf-8 -*-
"""Facit till bladen i lagstadiet.py: ett svar per uppgift, i bladets ordning. Läs om facit i bygg-banken.py."""

FACIT = {
    'ak1-matematik-tiokamrater': [
        '3  (7 + 3 = 10)',
        '7  (3 + 7 = 10)',
        '5  (5 + 5 = 10)',
        '1  (9 + 1 = 10)',
        '6  (6 + 4 = 10)',
        '8  (2 + 8 = 10)',
        '4  (6 + 4 = 10)',
        '2  (10 = 8 + 2)',
        'Eget svar. Två tal som blir 10 tillsammans, till exempel 1 + 9, 2 + 8, 3 + 7, 4 + 6, 5 + 5 eller 0 + 10.',
        '6. Bilden ska visa 10 prickar med 4 av dem inringade; 10 − 4 = 6 är inte inringade.',
    ],

    'ak2-svenska-stor-bokstav-och-punkt': [
        'Idag regnar det i Malmö.  (Också rätt: I dag regnar det i Malmö.) Malmö är en plats.',
        'Min hund heter Bamse.  (Bamse är ett namn på ett djur.)',
        'Vi ska åka till farmor på lördag.  (Bara Vi får stor bokstav: farmor och lördag skrivs med liten bokstav.)',
        'Elsa och Omar spelar fotboll.  (Elsa och Omar är namn.)',
        'Jag har en röd cykel.',
        'Eget svar. En hel mening om helgen som börjar med stor bokstav och slutar med punkt, och där namn har stor bokstav. Till exempel: I lördags badade jag med Ali.',
    ],

    'ak3-matematik-multiplikation': [
        '8',
        '30',
        '30',
        '14',
        '45',
        '80',
        '7  (7 · 5 = 35)',
        '9  (9 · 2 = 18)',
        '30 kakor. 6 · 5 = 30 (eller 5 + 5 + 5 + 5 + 5 + 5 = 30).',
        '40 kr. 4 · 10 = 40 (eller 10 + 10 + 10 + 10 = 40).',
    ],

    'ak1-matematik-plus-och-minus-till-20': [
        '13',
        '16',
        '12',
        '16',
        '12',
        '7',
        '8',
        '12',
        '13 äpplen  (9 + 4 = 13)',
        '9 fåglar  (14 − 5 = 9)',
    ],

    'ak1-matematik-storre-an-mindre-an-och-talfoljder': [
        '12 > 9',
        '5 < 8',
        '6 + 2 = 8',
        '14 < 17',
        '10 > 7 + 2  (7 + 2 = 9)',
        '10, 12  (två mer varje gång)',
        '25, 30  (fem mer varje gång)',
        '12, 10  (två mindre varje gång)',
        '13',
        '29',
        '50',
    ],

    'ak1-svenska-rimord': [
        'hus',
        'krok',
        'katt',
        'stol',
        'pil',
        'Eget svar. Ett ord som slutar som tak, till exempel bak, rak, smak eller vak.',
        'Eget svar. Ett ord som slutar som tåg, till exempel våg, såg, låg eller råg.',
        'Eget svar. Två bilder av saker vars namn rimmar, med orden under, till exempel katt och hatt, mus och hus eller sol och stol.',
    ],

    'ak1-svenska-las-och-svara-mias-hund': [
        'Pelle.  (Andra meningen: "Hunden heter Pelle.")',
        'Han är liten och brun.  ("Pelle är liten och brun.")',
        'En boll.  ("Han tycker om att leka med en boll.")',
        'Till parken.  ("De går till parken.")',
        'I sin korg.  (Sista meningen: "Hemma sover Pelle i sin korg.")',
        'Eget svar. En liten brun hund i en park, gärna med en boll.',
    ],

    'ak1-no-arstiderna': [
        'vår, sommar, höst, vinter',
        'Hösten.',
        'Vintern.',
        'Våren.',
        'Eget svar. Två varma kläder, till exempel mössa, vantar, halsduk, vinterjacka, overall eller vinterkängor.',
        'Eget svar. En årstid och ett skäl, till exempel: Sommaren, för då kan jag bada.',
        'Eget svar. En bild av sommaren, till exempel sol, gröna träd, blommor, bad eller glass.',
    ],

    'ak2-matematik-tiotal-och-ental': [
        '6 tiotal och 2 ental',
        '8 tiotal och 5 ental',
        '30  (34 = 30 + 4)',
        '79',
        '53',
        '46',
        '42',
        '70',
        '40',
        '38, 48, 83, 84',
        '2 tiotal och 3 ental. Bilden ska visa 23 prickar med två ringar om tio prickar var och 3 prickar utanför.',
    ],

    'ak2-matematik-klockan': [
        'Från vänster: 4.00, 9.00 och 12.00.',
        'Från vänster: 2.30 (halv tre), 8.30 (halv nio) och 11.30 (halv tolv).',
        'Sju: den korta visaren pekar på 7 och den långa på 12.\nHalv fem: den långa visaren pekar på 6 och den korta står mitt emellan 4 och 5.',
        'Om en timme: 4.00 (fyra)\nFör en timme sedan: 2.00 (två)',
        'Eget svar. En hel mening om vad eleven gör klockan sju på morgonen, till exempel: Klockan 7 äter jag frukost.',
    ],

    'ak2-matematik-pengar': [
        '8 kr',
        '25 kr',
        '30 kr',
        '11 kr  (2 + 2 + 2 + 5 = 11)',
        '3 kr  (10 − 7 = 3)',
        '5 kr  (20 − 15 = 5)',
        '14 kr  (8 + 6 = 14)',
        '20 kr  (50 − 30 = 20)',
        'Eget svar. Två olika sätt med mynt som blir 10 kr, till exempel 5 + 5, 5 + 2 + 2 + 1, 2 + 2 + 2 + 2 + 2 eller en tiokrona.',
        'Eget svar. Mynt som blir 12 kr, till exempel 10 kr + 2 kr, 5 kr + 5 kr + 2 kr eller 10 kr + 1 kr + 1 kr.',
    ],

    'ak2-svenska-substantiv-och-verb': [
        'Hunden och mattan.',
        'kastar',
        'cykel S, hoppar V, bord S, skrattar V',
        'Eget svar. Tre saker i klassrummet, till exempel bänk, tavla och penna.',
        'Eget svar. Tre saker man gör, till exempel springer, hoppar och leker.',
        'Till exempel dricker. Andra verb som passar: lapar, slickar, älskar.',
        'Eget svar. En hel mening med ordet cykel, med stor bokstav och punkt. Till exempel: Min cykel är blå.',
        'Eget svar. En hel mening med ordet springer, med stor bokstav och punkt. Till exempel: Hunden springer i parken.',
    ],

    'ak2-no-vaxtens-delar': [
        'Roten (rötterna).',
        'Stjälken.',
        'Blomman.',
        'Eget svar. Tre av: vatten, ljus (solljus), luft, näring ur jorden och värme.',
        'Eget svar. Till exempel mat (frukt, grönsaker, säd), syre att andas, trä eller papper.',
        'Eget svar. Blomman vissnar och dör till slut, för den behöver vatten för att leva.',
        'Eget svar. En växt med rot under jorden, en stjälk, minst ett blad och en blomma, med de fyra namnen utskrivna.',
    ],

    'ak3-matematik-addition-och-subtraktion-med-vaxling': [
        '84. Ental: 6 + 8 = 14, skriv 4 och växla 1 tiotal. Tiotal: 4 + 3 + 1 = 8.',
        '212. Ental: 7 + 5 = 12, växla 1. Tiotal: 2 + 8 + 1 = 11, växla 1. Hundratal: 1 + 1 = 2.',
        '623. Ental: 4 + 9 = 13, växla 1. Tiotal: 6 + 5 + 1 = 12, växla 1. Hundratal: 2 + 3 + 1 = 6.',
        '45. Växla ett tiotal: 13 − 8 = 5 ental, 6 − 2 = 4 tiotal.',
        '85. Växla ett tiotal: 12 − 7 = 5. Växla ett hundratal: 14 − 6 = 8.',
        '257. Växla i två steg: 400 = 3 hundratal, 9 tiotal och 10 ental. 10 − 3 = 7, 9 − 4 = 5, 3 − 1 = 2.',
        '353 böcker. 235 + 118 = 353 (5 + 8 = 13, växla 1; 3 + 1 + 1 = 5; 2 + 1 = 3).',
        '215 kr. 500 − 285: växla till 4 hundratal, 9 tiotal och 10 ental. 10 − 5 = 5, 9 − 8 = 1, 4 − 2 = 2.',
    ],

    'ak3-matematik-division-dela-lika': [
        '5',
        '3',
        '5',
        '6',
        '3',
        '8',
        '3 kex  (12 : 4 = 3)',
        '4 grupper  (20 : 5 = 4)',
        '3 · 7 = 21 (också rätt: 7 · 3 = 21)',
        'Eget svar. En berättelse där 8 saker delas lika på 2, så att var och en får 4. Till exempel: 8 bullar delas lika mellan 2 barn, och varje barn får 4.',
    ],

    'ak3-matematik-langd-och-mat': [
        '100 cm',
        '30 cm',
        '20 dm',
        '5 dm',
        '15 cm',
        '2 m',
        '1 cm, 15 cm, 2 dm, 1 m  (2 dm = 20 cm och 1 m = 100 cm)',
        '7 cm. 135 − 128 = 7.',
        '215 cm. 3 m = 300 cm, och 300 − 85 = 215.',
        'Eget svar. Ett uppmätt värde i hela centimeter; för ett barn i åk 3 är ungefär 13–18 cm rimligt.',
    ],

    'ak3-svenska-skriv-en-berattelse': [
        'Eget svar. Vem berättelsen handlar om (en person, ett djur eller en figur) och var den utspelar sig.',
        'Eget svar. 2–3 meningar som presenterar personen och platsen, gärna med början "En dag hittade ...". Stor bokstav och punkt.',
        'Eget svar. Något spännande eller roligt som händer, ett problem eller en överraskning, som hänger ihop med början.',
        'Eget svar. Ett slut där det som hände löser sig, till exempel att problemet blir löst eller att personen kommer hem.',
        'Eget svar. En kort rubrik som passar berättelsen och gör en nyfiken, till exempel "Nyckeln i sanden".',
    ],

    'ak3-engelska-colours-and-numbers': [
        'red',
        'blue',
        'yellow',
        'green',
        'seven = 7, ten = 10, four = 4',
        '3 = three, 5 = five, 8 = eight',
        'three, six  (one, two, three, four, five, six)',
        'yellow  (The sun is yellow.)',
        'green  (Grass is green.)',
        'Eget svar. En färg på engelska, till exempel My favourite colour is blue.',
    ],
}
