# -*- coding: utf-8 -*-
"""Övningsblad för Gymnasiet, år 1–3. Format och regler: se verktyg/bygg-banken.py."""
from figurer import *  # noqa: F401,F403

BLAD = [
    dict(fil='gy1-matematik-ekvationer-och-potenser', arskurs='gy1', amne='Matematik',
         titel='Ekvationer och potenser', omrade='Matematik 1 / nivå 1', tid='35 minuter',
         instruktion=['Lös ekvationerna och förenkla uttrycken.',
                      'Redovisa varje steg – det är stegen som visar att du förstått.'],
         uppgifter=[('Lös 4x − 7 = 21.', 2), ('Lös 3(x + 2) = 2x + 11.', 2),
                    ('Lös x/5 + 3 = 7.', 2), ('Förenkla 2³ · 2⁴.', 1), ('Förenkla (5x)².', 1),
                    ('Skriv 0,00042 i grundpotensform.', 1),
                    ('En mobil kostar 6 000 kr och minskar i värde med 15 % per år. '
                     'Vad är den värd efter 2 år?', 2)],
         beskrivning='Förstagradsekvationer, potenslagar, grundpotensform och procentuell minskning.'),

    dict(fil='gy2-matematik-andragradsekvationer', arskurs='gy2', amne='Matematik',
         titel='Andragradsekvationer', omrade='Matematik 2 / nivå 2', tid='40 minuter',
         instruktion=['En ekvation på formen x² + px + q = 0 kan lösas med pq-formeln:',
                      'x = −p/2 ± √((p/2)² − q)',
                      'Kontrollera svaren genom att sätta in dem i ekvationen.'],
         uppgifter=[('Lös x² = 49.', 1), ('Lös x² − 6x + 8 = 0.', 2), ('Lös x² + 2x − 15 = 0.', 2),
                    ('Lös 2x² − 8x − 10 = 0. Tips: dela först med 2.', 2),
                    ('Lös x(x − 4) = 0.', 1),
                    ('Har x² + 4x + 5 = 0 några reella lösningar? Motivera.', 2),
                    ('En rektangel har arean 24 cm², och den ena sidan är 2 cm längre än den andra. '
                     'Ställ upp en ekvation och bestäm sidornas längd.', 2)],
         beskrivning='pq-formeln, nollproduktmetoden, diskriminanten och en areauppgift.'),

    dict(fil='gy3-matematik-derivata', arskurs='gy3', amne='Matematik',
         titel='Derivata – grunderna', omrade='Matematik 3', tid='40 minuter',
         instruktion=['Derivatan f′(x) anger hur snabbt f(x) ändras – lutningen på kurvans tangent.',
                      'Deriveringsregeln: om f(x) = xⁿ så är f′(x) = n · xⁿ⁻¹.'],
         uppgifter=[('Derivera f(x) = x⁵.', 1), ('Derivera f(x) = 4x³ − 2x + 7.', 1),
                    ('Beräkna f′(2) om f(x) = x² + 3x.', 2),
                    ('Derivera f(x) = 6/x. Tips: skriv först om som 6x⁻¹.', 1),
                    ('Bestäm lutningen på tangenten till y = x³ i punkten där x = −1.', 2),
                    ('För vilket x har f(x) = x² − 8x + 3 en extrempunkt? Är det ett max eller ett min?', 2),
                    ('En boll kastas uppåt och har höjden h(t) = 20t − 5t² meter efter t sekunder. '
                     'Beräkna h′(1) och förklara vad svaret betyder.', 2)],
         beskrivning='Deriveringsregler, tangentens lutning, extrempunkt och en tillämpning.'),

    # ---- Gymnasiet 1 ----
    dict(fil='gy1-matematik-volym-skala-och-likformighet', arskurs='gy1', amne='Matematik',
         titel='Volym, skala och likformighet', omrade='Matematik 1 / nivå 1: geometri', tid='35 minuter',
         instruktion=['Volym: rätblock b · l · h, cylinder π · r² · h, kon (π · r² · h) / 3, klot (4 · π · r³) / 3. 1 dm³ = 1 liter.',
                      'Skala 1 : n betyder att 1 cm på kartan är n cm i verkligheten.',
                      'Om längdskalan mellan två likformiga figurer är k blir areaskalan k² och volymskalan k³.'],
         uppgifter=[('Beräkna volymen av en cylinder med radien 3 cm och höjden 10 cm. Svara med ett heltal. [[]] cm³', 1),
                    ('Beräkna volymen av en kon med radien 4 cm och höjden 9 cm. Svara med ett heltal. [[]] cm³', 1),
                    ('Beräkna volymen av ett klot med radien 6 cm. Svara med ett heltal. [[]] cm³', 1),
                    ('Ett akvarium är 60 cm långt, 30 cm brett och 40 cm högt. Hur många liter vatten rymmer det? [] liter', 1),
                    ('På en karta i skala 1 : 50 000 är avståndet mellan två orter 8 cm. Hur långt är det i verkligheten? [] km', 1),
                    ('En burk är en cylinder som rymmer 1,0 liter och har diametern 10 cm. Hur hög är burken? Svara med en decimal. [[]] cm', 2),
                    ('Två likformiga trianglar har motsvarande sidor som är 6 cm och 15 cm. Den mindre har arean 20 cm². '
                     'Hur stor är arean av den större? [[]] cm²', 2)],
         beskrivning='Volym av cylinder, kon och klot, skala på karta och likformighet med längd-, area- och volymskala.'),

    dict(fil='gy1-matematik-linjara-modeller', arskurs='gy1', amne='Matematik',
         titel='Linjära modeller – jämför tre avtal', omrade='Matematik 1 / nivå 1: samband och förändring', tid='35 minuter',
         instruktion=['Ett linjärt samband har formen y = kx + m. k är förändringen per enhet och m är startvärdet.',
                      'Två linjer skär varandra där y-värdena är lika: sätt de två uttrycken lika med varandra och lös ekvationen.'],
         text=('Tre mobilabonnemang. A: 120 kr i månaden plus 20 kr per GB. B: 300 kr i månaden med obegränsat antal GB. '
               'C: 200 kr i månaden plus 10 kr per GB.'),
         uppgifter=[('Skriv en formel för kostnaden y kr för abonnemang A efter x GB.', 1),
                    ('Vid hur många GB kostar A och B lika mycket? Ställ upp och lös en ekvation. [] GB', 1),
                    ('Vilket abonnemang är billigast vid 15 GB? Visa med en uträkning.', 1),
                    ('Vad betyder talen 20 och 120 i formeln för A?', 1),
                    ('För vilka antal GB är C billigare än A? Lös olikheten.', 1),
                    ('Bestäm k och m för linjen genom punkterna (2, 7) och (6, 19). k = []   m = []', 1),
                    ('Rita graferna för A och B i samma koordinatsystem (x: 0–12 GB, y: 0–400 kr).', 'ruta')],
         beskrivning='Linjära modeller för tre abonnemang: formler, skärningspunkt, olikhet, tolkning av k och m och en graf.'),

    dict(fil='gy1-svenska-retorik', arskurs='gy1', amne='Svenska',
         titel='Retorik – ethos, pathos och logos', omrade='Svenska 1 / nivå 1: tala och övertyga', tid='40 minuter',
         instruktion=['Retorik är konsten att övertyga. Ethos är talarens trovärdighet, pathos är känslor och logos är fakta och logiska argument.',
                      'Mottagare, syfte och situation styr hur man formulerar sig. Talet nedan är ett påhittat exempel.'],
         text=('Kära klasskamrater. Jag har gått i den här skolan i två år, och jag har sett något hända. Förr satt vi i matsalen och '
               'pratade. I dag sitter många med blicken i mobilen. Därför tycker jag att vår skola ska införa mobilfria raster. '
               'Som ordförande i elevrådet har jag pratat med över hundra elever, och de flesta säger att de saknar att umgås på '
               'riktigt. Tänk dig en rast där du hör någons skratt i stället för en notis. Rasten finns för att vi ska vila hjärnan '
               'och träffa varandra. Mobilfria raster är därför inte ett förbud, utan en gåva till oss alla.'),
         uppgifter=[('Vad är talarens tes? Svara med en mening.', 1),
                    ('Ge ett exempel på ethos i talet.', 1),
                    ('Ge ett exempel på pathos i talet.', 1),
                    ('Vilket argument bygger mest på logos? Motivera.', 1),
                    ('Vem är mottagaren och vad är talets syfte?', 1),
                    ('Vilka svagheter har talet och vad skulle göra det mer övertygande?', 2)],
         beskrivning='Analysera ett påhittat tal med retorikens begrepp ethos, pathos och logos, mottagare, syfte och svagheter.'),

    dict(fil='gy1-engelska-formal-email', arskurs='gy1', amne='Engelska',
         titel='Writing a formal email', omrade='Engelska 5 / nivå 1: skriva', tid='35 minuter',
         instruktion=['A formal email is polite and clear: use full forms (I am, not I\'m), no slang, and state your purpose early.',
                      'Layout: greeting, reason for writing, details, polite closing, name. Useful phrases: I am writing to ..., '
                      'Could you please ..., I look forward to hearing from you.',
                      'I brittisk engelska följer avslutningen av hälsningen: Dear Mr Smith → Yours sincerely. Dear Sir or Madam → Yours faithfully.'],
         uppgifter=[('Skriv om till formell engelska: "Hey! Can u send me the info about the course asap?"', 3),
                    ('Skriv om till en formell avslutning: "Thanks a lot, bye!"', 1),
                    ('Vilken avslutning passar efter "Dear Ms Taylor,"? ___', 0),
                    ('Vilken avslutning passar efter "Dear Sir or Madam,"? ___', 0),
                    ('Vilken mening är mest formell? a) I wanna know the price.  b) I would like to know the price. ___', 0),
                    ('Write a formal email (about 80 words) to a language school. Ask about the price, the start date and accommodation.', 8)],
         beskrivning='Formella mejl på engelska: formulera om, välja avslutning och skriva ett eget mejl till en språkskola.'),

    dict(fil='gy1-no-kemi-mol-och-substansmangd', arskurs='gy1', amne='NO / Fysik / Kemi / Biologi', chip='Kemi',
         titel='Mol och substansmängd', omrade='Kemi 1: kvantitativ kemi', tid='40 minuter',
         instruktion=['Substansmängd n mäts i mol: n = m / M, där m är massan i gram och M molmassan i g/mol. Koncentration c = n / V (mol/dm³).',
                      'Molmassor (g/mol): H 1,0   C 12,0   O 16,0   Na 23,0   Cl 35,5   Ca 40,1. Avogadros konstant: 6,02 · 10²³ per mol.'],
         uppgifter=[('Beräkna molmassan för vatten, H₂O. [[]] g/mol', 0),
                    ('Hur många mol är 36 g vatten? [] mol', 0),
                    ('Beräkna massan av 0,50 mol natriumklorid, NaCl. [[]] g', 1),
                    ('Beräkna molmassan för kalciumkarbonat, CaCO₃. [[]] g/mol', 1),
                    ('Hur många gram väger 3,0 mol koldioxid, CO₂? [[]] g', 1),
                    ('Du löser 0,50 mol natriumhydroxid i vatten till 2,0 dm³ lösning. Beräkna koncentrationen. [[]] mol/dm³', 1),
                    ('Hur många mol finns i 250 cm³ lösning med koncentrationen 0,20 mol/dm³? [[]] mol', 1),
                    ('Hur många molekyler finns i 0,50 mol av ett ämne? Svara med tiopotens. [[]]', 1),
                    ('Vätgas förbränns: 2 H₂ + O₂ → 2 H₂O. Hur många mol vatten bildas av 4,0 mol H₂, och hur många mol O₂ går åt? '
                     '[] mol H₂O och [] mol O₂', 1)],
         beskrivning='Mol, molmassa och koncentration: räkna med substansmängd, antal partiklar och reaktionsformler.'),

    dict(fil='gy1-programmering-listor-och-funktioner', arskurs='gy1', amne='Programmering',
         titel='Python: listor, funktioner och loopar', omrade='Programmering 1', tid='40 minuter',
         instruktion=['En lista samlar värden: tal = [4, 8, 15]. Första elementet har index 0, och len(tal) är antalet element. // ger heltalsdivision och % rest.',
                      'En funktion definieras med def och lämnar tillbaka ett värde med return. En while-loop körs så länge villkoret är sant.',
                      'tal.append(x) lägger till x sist i listan, och s.upper() gör om texten till versaler. for o in orden går igenom listan ett element i taget.'],
         uppgifter=[('Vad skriver programmen ut? a) []   b) []', 0,
                     kodrad(('a)', 'tal = [4, 8, 15]\nprint(tal[1])'),
                            ('b)', 'tal = [2, 4, 6]\ntal.append(8)\nprint(len(tal))'))),
                    ('c) Vad skrivs ut? []   d) Vad skrivs ut? Skriv raderna efter varandra. ___', 0,
                     kodrad(('c)', 'def dubbla(x):\n    return x * 2\nprint(dubbla(5) + 1)'),
                            ('d)', 'orden = ["kal", "ba", "lo"]\nfor o in orden:\n    print(o.upper())'))),
                    ('e) Vad skrivs ut? []   f) Vad skrivs ut? ___', 0,
                     kodrad(('e)', 'x = 10\nwhile x > 3:\n    x = x - 4\nprint(x)'),
                            ('f)', 'a = 7\nb = 2\nprint(a // b, a % b)'))),
                    ('Skriv en funktion kvadrat(x) som lämnar tillbaka x upphöjt till 2.', 1),
                    ('Skriv kod som summerar talen i listan tal = [3, 5, 9] med en for-loop och skriver ut summan.', 2)],
         beskrivning='Läsa och skriva Python med listor, funktioner, while- och for-loopar samt heltalsdivision och rest.'),

    # ---- Gymnasiet 2 ----
    dict(fil='gy2-matematik-exponentialfunktioner', arskurs='gy2', amne='Matematik',
         titel='Exponentialfunktioner och logaritmer', omrade='Matematik 2 / nivå 2', tid='40 minuter',
         instruktion=['En exponentialfunktion har formen y = C · aˣ. C är startvärdet och a är tillväxtfaktorn.',
                      'Logaritmen lg x är det tal man ska upphöja 10 till för att få x: lg 1000 = 3.',
                      'Ekvationen aˣ = b har lösningen x = lg b / lg a. Använd räknare där det behövs.'],
         uppgifter=[('Beräkna 2⁵ = [] och 5⁻² = [[]]', 0),
                    ('Beräkna lg 100 = [] och lg 0,01 = [] utan räknare.', 0),
                    ('Lös 2ˣ = 64 utan räknare. x = []', 0),
                    ('Lös 3ˣ = 20 med räknare. Svara med två decimaler. x = [[]]', 1),
                    ('En bakteriekultur har 500 bakterier och antalet fördubblas varje timme. Skriv en funktion för antalet y efter x timmar.', 1),
                    ('Hur många bakterier finns det efter 6 timmar? [[]]', 0),
                    ('Efter hur lång tid finns det 100 000 bakterier? Svara med två decimaler. [[]] timmar', 1),
                    ('Ett ämne halveras var 5:e år. Hur stor andel finns kvar efter 15 år? [[]]', 0),
                    ('En bil värd 200 000 kr minskar i värde med 12 % per år. Vad är den värd efter 4 år? Avrunda till hundratal kronor.', 1)],
         beskrivning='Exponentialfunktioner, tillväxtfaktor och logaritmer: lösa exponentialekvationer och tolka tillväxt och avtagande.'),

    dict(fil='gy2-matematik-trigonometri', arskurs='gy2', amne='Matematik',
         titel='Trigonometri – räta och allmänna trianglar', omrade='Matematik 1 och 3: trigonometri', tid='40 minuter',
         instruktion=['I en rätvinklig triangel: sin v = motstående / hypotenusan, cos v = närliggande / hypotenusan, tan v = motstående / närliggande.',
                      'Sinussatsen: a / sin A = b / sin B. Cosinussatsen: a² = b² + c² − 2bc · cos A. Area: T = (b · c · sin A) / 2.',
                      'Ställ in räknaren på grader. Svara med en decimal om inget annat anges.'],
         uppgifter=[('Beräkna längden x. [] cm', 0,
                     triangel(5.736, 8.192, 10, sida_a='x', sida_c='10 cm', vinklar=('35°', '', ''), rattvinkel='C', hojd=110)),
                    ('I en rätvinklig triangel är den närliggande kateten 8 cm och den motstående 6 cm. Beräkna vinkeln v. [[]] °', 0),
                    ('En stege är 4,0 m lång och bildar vinkeln 70° med marken. Hur högt upp når den? [] m', 0),
                    ('I en triangel är A = 40°, B = 65° och a = 8 cm. Beräkna sidan b. [[]] cm', 1),
                    ('I en triangel är b = 7 cm, c = 9 cm och vinkeln A = 50° mellan dem. Beräkna sidan a. [] cm', 1),
                    ('Beräkna arean av triangeln i uppgiften ovan. [[]] cm²', 1),
                    ('Beräkna sin 30° = [] och cos 60° = [] utan räknare.', 0),
                    ('Från en punkt 50 m från ett torn är höjdvinkeln till tornets topp 32°. Hur högt är tornet? [[]] m', 1)],
         beskrivning='Sinus, cosinus och tangens i räta trianglar samt sinussatsen, cosinussatsen och areaformeln.'),

    dict(fil='gy2-matematik-sannolikhet-och-kombinatorik', arskurs='gy2', amne='Matematik',
         titel='Sannolikhet och kombinatorik', omrade='Matematik: sannolikhet och kombinatorik', tid='40 minuter',
         instruktion=['Sannolikhet = gynnsamma utfall / alla utfall. I ett träddiagram multiplicerar du längs en gren och adderar mellan grenar.',
                      'Utan återläggning ändras sannolikheterna för nästa dragning.',
                      'Antal sätt att ordna n olika saker är n! = n · (n − 1) · ... · 1. Att välja k av n utan hänsyn till ordning kan göras på n! / (k! · (n − k)!) sätt.'],
         uppgifter=[('En påse har 3 röda och 2 blå kulor. Du drar två kulor utan återläggning. Rita ett träddiagram och beräkna sannolikheten för två röda.', 3),
                    ('Beräkna sannolikheten att få en kula av varje färg i uppgiften ovan.', 1),
                    ('Samma påse, men du lägger tillbaka den första kulan innan du drar nästa. Vad är sannolikheten för två röda?', 1),
                    ('Två tärningar kastas. Vad är sannolikheten att summan blir 7?', 1),
                    ('Hur många olika fyrsiffriga koder kan man bilda med siffrorna 0–9 om siffrorna får upprepas? [[]]', 0),
                    ('På hur många sätt kan 5 personer ställa sig i en kö? [[]]', 0),
                    ('Ett lag på 6 personer ska välja 2 till ett uppdrag. På hur många sätt kan det göras? []', 0),
                    ('Vad är sannolikheten att få minst en sexa när man kastar en tärning tre gånger? Tips: använd komplementhändelsen.', 2)],
         beskrivning='Träddiagram med och utan återläggning, tärningskast, permutationer, kombinationer och komplementhändelse.'),

    dict(fil='gy2-svenska-kallkritik', arskurs='gy2', amne='Svenska',
         titel='Källkritik', omrade='Svenska 2: sakprosa och källor', tid='35 minuter',
         instruktion=['Fyra frågor att ställa till en källa: Är den äkta? Är den beroende av andra källor? Är den samtida, det vill säga nära i tid och rum? '
                      'Finns det en tendens, alltså ett syfte eller intresse bakom?',
                      'En primärkälla kommer direkt från händelsen. En sekundärkälla beskriver den i efterhand.'],
         uppgifter=[('Du hittar en blogg där en säljare av kosttillskott skriver att produkten botar trötthet. Vilket källkritiskt kriterium är viktigast? Förklara.', 2),
                    ('Ett inlägg i sociala medier visar en bild "från gårdagens översvämning", men bilden är tre år gammal. Vilket eller vilka kriterier brister? Förklara.', 2),
                    ('Tre tidningar publicerar exakt samma text om en händelse, eftersom alla fått den från samma nyhetsbyrå. Är det tre oberoende källor? Förklara.', 1),
                    ('Förklara skillnaden mellan primärkälla och sekundärkälla. Ge ett exempel på vardera.', 2),
                    ('Hur kan du kontrollera att ett påstående du läst på nätet stämmer? Nämn tre sätt.', 2),
                    ('Skriv en bedömning (3–4 meningar) av en källa som du själv använder när du söker information.', 4)],
         beskrivning='Källkritiska kriterier och begrepp: äkthet, beroende, samtidighet, tendens, primär- och sekundärkälla.'),

    dict(fil='gy2-engelska-analysing-a-short-text', arskurs='gy2', amne='Engelska',
         titel='Analysing a short text', omrade='Engelska 6 / nivå 2: litteratur', tid='40 minuter',
         instruktion=['Read the text carefully. Answer the questions in English, in full sentences.',
                      'Support your answers with short quotes from the text.'],
         text=("The last bus of the night left without her. Mira stood under the flickering streetlamp and watched its red "
               "lights shrink into the dark. She had promised her mother she would be home by ten. Now it was almost "
               "midnight, and her phone was dead. For a moment she wanted to cry. Then she noticed the snow falling quietly "
               "around her, soft as feathers, covering the whole street in white. She tucked her scarf tighter, took a deep "
               "breath, and began to walk. The road was long, but it was hers to walk, and for the first time all week the "
               "silence did not feel empty."),
         uppgifter=[('Describe the setting: time, place and weather.', 1),
                    ('Is the narrator in the first or the third person? How can you tell?', 1),
                    ("How does Mira's mood change during the text? Quote two phrases that show it.", 2),
                    ('What might the flickering streetlamp and the snow symbolise?', 2),
                    ('Explain the last sentence: "the silence did not feel empty".', 2),
                    ('Write a short paragraph (3–4 lines) that continues the story in the same tone.', 3)],
         beskrivning='Analysera en kort originaltext på engelska: miljö, berättare, stämning, symbolik och eget fortsatt skrivande.'),

    dict(fil='gy2-fysik-rorelse-och-newtons-lagar', arskurs='gy2', amne='NO / Fysik / Kemi / Biologi', chip='Fysik',
         titel='Rörelse och Newtons lagar', omrade='Fysik 1: mekanik', tid='40 minuter',
         instruktion=['Medelhastighet v = s / t. Likformigt accelererad rörelse: v = v₀ + a · t och s = v₀ · t + a · t² / 2.',
                      'Newtons andra lag: F = m · a. Tyngd: F = m · g, där g = 9,82 m/s². 1 m/s = 3,6 km/h.',
                      'Skriv med lämpligt antal värdesiffror.'],
         uppgifter=[('En bil kör 150 km på 2,0 h. Beräkna medelhastigheten i km/h och i m/s. [] km/h  och  [] m/s', 0),
                    ('Omvandla 90 km/h till m/s. [] m/s', 0),
                    ('En cyklist accelererar från stillastående till 8,0 m/s på 4,0 s. Beräkna accelerationen. [] m/s²', 1),
                    ('Hur lång sträcka tillryggalägger cyklisten under dessa 4,0 s? [] m', 1),
                    ('Vilken kraft krävs för att ge en låda med massan 12 kg accelerationen 1,5 m/s²? Friktionen försummas. [] N', 1),
                    ('Beräkna tyngden av en person med massan 70 kg. [[]] N', 1),
                    ('En sten släpps från en klippa och faller i 3,0 s. Luftmotståndet försummas. Hur fort rör den sig då? [] m/s', 1),
                    ('Hur högt är klippan i uppgiften ovan? [] m', 1),
                    ('Förklara Newtons första lag med ett exempel från vardagen.', 2)],
         beskrivning='Hastighet, acceleration, Newtons lagar och fritt fall: räkna med v, s, a, F och tyngd.'),

    # ---- Gymnasiet 3 ----
    dict(fil='gy3-matematik-integraler', arskurs='gy3', amne='Matematik',
         titel='Integraler – primitiva funktioner och area', omrade='Matematik 3', tid='40 minuter',
         instruktion=['En primitiv funktion F(x) till f(x) uppfyller F′(x) = f(x). Regeln: ∫ xⁿ dx = xⁿ⁺¹ / (n + 1) + C när n ≠ −1.',
                      'Bestämd integral: ∫ f(x) dx från a till b är F(b) − F(a). Om f(x) ≥ 0 är det arean under kurvan.'],
         uppgifter=[('Bestäm ∫ x⁴ dx.', 1), ('Bestäm ∫ (6x² − 4x + 3) dx.', 1),
                    ('Beräkna ∫ 3x² dx från x = 0 till x = 2. []', 1),
                    ('Beräkna ∫ (2x + 1) dx från x = 1 till x = 4. []', 1),
                    ('Beräkna ∫ 1/x² dx från x = 1 till x = 2. Tips: 1/x² = x⁻². []', 1),
                    ('Beräkna arean mellan kurvan y = x² + 1, x-axeln och linjerna x = 0 och x = 3. []', 1),
                    ('Beräkna arean mellan kurvorna y = x och y = x² mellan deras skärningspunkter.', 2),
                    ('Bestäm funktionen f(x) om f′(x) = 4x − 3 och f(1) = 5.', 2)],
         beskrivning='Primitiva funktioner, bestämda integraler och area mellan kurvor.'),

    dict(fil='gy3-matematik-trigonometriska-ekvationer', arskurs='gy3', amne='Matematik',
         titel='Radianer och trigonometriska ekvationer', omrade='Matematik 4: trigonometri', tid='40 minuter',
         instruktion=['180° = π radianer. På enhetscirkeln är cos v och sin v punktens x- och y-koordinat.',
                      'sin x = a ger x = arcsin a + n · 360° och x = 180° − arcsin a + n · 360°. cos x = a ger x = ± arccos a + n · 360°. '
                      'tan x = a ger x = arctan a + n · 180°.'],
         uppgifter=[('Skriv 60° och 225° i radianer. [[]] och [[]]', 0),
                    ('Skriv π/6 rad och 3π/2 rad i grader. [] ° och [[]] °', 0),
                    ('Lös sin x = 0,5 för 0° ≤ x ≤ 360°. x = [[]] ° eller [[]] °', 0),
                    ('Lös cos x = −0,5 för 0° ≤ x ≤ 360°. x = [[]] ° eller [[]] °', 0),
                    ('Lös tan x = 1 för 0° ≤ x ≤ 360°. x = [[]] ° eller [[]] °', 0),
                    ('Lös 2 sin x − 1 = 0 för 0 ≤ x ≤ 2π. Svara exakt i radianer. ___', 1),
                    ('Lös sin x = 0,3 för 0° ≤ x ≤ 360° med räknare. Svara med en decimal. ___', 1),
                    ('Lös cos x = 0,8 allmänt, med en decimal. ___', 1),
                    ('Ange amplitud och period för y = 3 sin 2x. Amplitud: []  Period: [[]] °', 0)],
         beskrivning='Radianer och enhetscirkeln, lösa trigonometriska ekvationer och läsa av amplitud och period.'),

    dict(fil='gy3-svenska-referat-och-sammanfattning', arskurs='gy3', amne='Svenska',
         titel='Referera, parafrasera och sammanfatta', omrade='Svenska 3 / nivå 3: vetenskapligt skrivande', tid='40 minuter',
         instruktion=['Att citera är att återge ord för ord inom citattecken. Att parafrasera är att återge idén med egna ord. '
                      'Att sammanfatta är att korta ner det viktigaste.',
                      'Ett referat är sakligt: presens, inga egna åsikter, och med hänvisning till källan.'],
         text=['Under sömnen vilar inte hjärnan, den arbetar. Forskning om sömn visar att minnen som skapats under dagen '
               'befästs under natten, särskilt under djupsömnen. Det betyder att den som sover efter att ha pluggat ofta minns '
               'mer än den som är vaken. Under sömnen sorterar hjärnan också bort mindre viktig information och stärker det som verkar '
               'viktigt. Tonåringar behöver i regel åtta till tio timmar sömn per natt, men många sover betydligt mindre, bland '
               'annat eftersom den biologiska klockan under tonåren förskjuts mot senare kvällar. Skolor i flera länder har därför '
               'prövat senare skolstart. Resultaten har varit blandade, men många elever uppger att de känner sig piggare.',
               'Källa: Nextrum, exempeltext om sömn och minne.'],
         uppgifter=[('Vilket är textens huvudbudskap? Svara med en mening.', 1),
                    ('Skriv ett referat av texten på högst 60 ord.', 4),
                    ('Förklara skillnaden mellan att citera, parafrasera och sammanfatta.', 2),
                    ('Vilka påståenden i texten skulle behöva en källa för att vara trovärdiga?', 2),
                    ('Formulera en forskningsfråga som skulle kunna undersöka sambandet mellan sömn och provresultat.', 1)],
         beskrivning='Referera, parafrasera och sammanfatta en saklig text om sömn och minne, och formulera en forskningsfråga.'),

    dict(fil='gy3-engelska-argumentative-essay', arskurs='gy3', amne='Engelska',
         titel='Writing an argumentative essay', omrade='Engelska 6 / nivå 2: skriva', tid='45 minuter',
         instruktion=['A strong argumentative text has a clear thesis, paragraphs that each make one point, a counterargument with a rebuttal, and a conclusion.',
                      'Connectors guide the reader: however (contrast), for example, therefore (result), in addition.'],
         uppgifter=[('Write a thesis statement for the topic "Social media does more harm than good".', 2),
                    ('Match each connector with its function: however, for example, therefore, in addition. '
                     'Functions: adds a point, gives an example, shows contrast, shows a result.', 2),
                    ('Improve this sentence: "Social media is bad because it is bad for people."', 2),
                    ('Write a topic sentence for a paragraph arguing that young people learn useful skills online.', 1),
                    ('Write one counterargument and a rebuttal to it.', 3),
                    ('Write a concluding paragraph of about five lines.', 5)],
         beskrivning='Skriva en argumenterande text på engelska: tes, bindeord, ämnesmening, motargument med bemötande och avslutning.'),

    dict(fil='gy3-so-ekonomi-bnp-inflation-och-riksbanken', arskurs='gy3', amne='SO / Historia / Samhällskunskap', chip='Samhällskunskap',
         titel='Ekonomi: BNP, inflation och Riksbanken', omrade='Samhällskunskap', tid='40 minuter',
         instruktion=['BNP (bruttonationalprodukten) är värdet av alla varor och tjänster som produceras i ett land under ett år.',
                      'Inflation är när priserna i allmänhet stiger. Riksbanken har som mål att inflationen ska vara 2 procent och påverkar den bland annat genom styrräntan.',
                      'Konjunktur är svängningarna i ekonomin: högkonjunktur och lågkonjunktur.'],
         uppgifter=[('Förklara med egna ord vad BNP mäter.', 2),
                    ('En vara kostade 400 kr förra året och kostar 420 kr i år. Hur många procent har priset ökat? [] %', 0),
                    ('Lönen är oförändrad men priserna stiger med 3 procent. Vad händer med köpkraften? ___', 0),
                    ('Lönen ökar nominellt med 3 procent och inflationen är 2 procent. Ungefär hur stor är löneökningen räknat i köpkraft? [] %', 0),
                    ('Vad händer vanligen med inflationen när Riksbanken höjer styrräntan? Förklara kedjan steg för steg.', 2),
                    ('Nämn tre tecken på en lågkonjunktur.', 2),
                    ('Ge ett exempel på en inkomst och ett exempel på en utgift i statens budget.', 1),
                    ('Förklara vad progressiv skatt innebär. Ge ett argument för och ett argument mot.', 2)],
         beskrivning='BNP, inflation, reallön, styrränta, konjunktur och statens budget: begrepp och enkla uträkningar.'),

    dict(fil='gy3-biologi-fran-dna-till-protein', arskurs='gy3', amne='NO / Fysik / Kemi / Biologi', chip='Biologi',
         titel='Från DNA till protein', omrade='Biologi 1: genetik', tid='40 minuter',
         instruktion=['DNA har fyra baser: adenin (A), tymin (T), cytosin (C) och guanin (G). A binder till T och C binder till G.',
                      'Transkription: en gen skrivs av till mRNA i cellkärnan. I RNA ersätts T av U (uracil).',
                      'Translation: ribosomerna läser mRNA tre baser i taget (kodon) och bygger ett protein av aminosyror.',
                      'mRNA bildas komplementärt mot templatsträngen: A ger U, T ger A, C ger G och G ger C.'],
         uppgifter=[('Skriv den komplementära DNA-strängen till TACGGCAT. ___', 0),
                    ('DNA-strängen TACGGCAT är templatsträng. Vilken mRNA-sekvens bildas vid transkriptionen? ___', 0),
                    ('Hur många baser utgör ett kodon, och vad kodar ett kodon för? ___', 1),
                    ('Var i cellen sker translationen? ___', 1),
                    ('En gen har 300 baspar. Hur många aminosyror kodar den för som mest? [[]]', 0),
                    ('Vad är en mutation? Ge ett exempel på en möjlig följd.', 2),
                    ('Förklara skillnaden mellan transkription och translation.', 3),
                    ('Nästan alla celler i kroppen har samma DNA. Varför kan en hudcell och en nervcell ändå se ut och fungera olika?', 2)],
         beskrivning='DNA, basparning, transkription, translation och mutationer: räkna med baser och kodon och förklara genuttryck.'),

]
