# -*- coding: utf-8 -*-
"""Övningsblad för Gymnasiet, år 1–3. Format och regler: se verktyg/bygg-banken.py."""
from figurer import *  # noqa: F401,F403

BLAD = [
    dict(fil='gy1-matematik-ekvationer-och-potenser', arskurs='gy1', amne='Matematik',
         titel='Ekvationer och potenser', omrade='Matematik 1 / nivå 1', tid='35 minuter',
         instruktion=['Lös ekvationerna och förenkla uttrycken.',
                      'Redovisa varje steg – det är stegen som visar att du förstått.'],
         uppgifter=[('Lös 4x − 7 = 21.', 2), ('Lös 3(x + 2) = 2x + 11.', 2),
                    ('Lös x/5 + 3 = 7.', 2), ('Förenkla 2³ · 2⁴.', 1), ('Förenkla (5x)².', 1),
                    ('Skriv 0,00042 i grundpotensform.', 1),
                    ('En mobil kostar 6 000 kr och minskar i värde med 15 % per år. '
                     'Vad är den värd efter 2 år?', 2)],
         beskrivning='Förstagradsekvationer, potenslagar, grundpotensform och procentuell minskning.'),

    dict(fil='gy2-matematik-andragradsekvationer', arskurs='gy2', amne='Matematik',
         titel='Andragradsekvationer', omrade='Matematik 2 / nivå 2', tid='40 minuter',
         instruktion=['En ekvation på formen x² + px + q = 0 kan lösas med pq-formeln:',
                      'x = −p/2 ± √((p/2)² − q)',
                      'Kontrollera svaren genom att sätta in dem i ekvationen.'],
         uppgifter=[('Lös x² = 49.', 1), ('Lös x² − 6x + 8 = 0.', 2), ('Lös x² + 2x − 15 = 0.', 2),
                    ('Lös 2x² − 8x − 10 = 0. Tips: dela först med 2.', 2),
                    ('Lös x(x − 4) = 0.', 1),
                    ('Har x² + 4x + 5 = 0 några reella lösningar? Motivera.', 2),
                    ('En rektangel har arean 24 cm², och den ena sidan är 2 cm längre än den andra. '
                     'Ställ upp en ekvation och bestäm sidornas längd.', 2)],
         beskrivning='pq-formeln, nollproduktmetoden, diskriminanten och en areauppgift.'),

    dict(fil='gy3-matematik-derivata', arskurs='gy3', amne='Matematik',
         titel='Derivata – grunderna', omrade='Matematik 3', tid='40 minuter',
         instruktion=['Derivatan f′(x) anger hur snabbt f(x) ändras – lutningen på kurvans tangent.',
                      'Deriveringsregeln: om f(x) = xⁿ så är f′(x) = n · xⁿ⁻¹.'],
         uppgifter=[('Derivera f(x) = x⁵.', 1), ('Derivera f(x) = 4x³ − 2x + 7.', 1),
                    ('Beräkna f′(2) om f(x) = x² + 3x.', 2),
                    ('Derivera f(x) = 6/x. Tips: skriv först om som 6x⁻¹.', 1),
                    ('Bestäm lutningen på tangenten till y = x³ i punkten där x = −1.', 2),
                    ('För vilket x har f(x) = x² − 8x + 3 en extrempunkt? Är det ett max eller ett min?', 2),
                    ('En boll kastas uppåt och har höjden h(t) = 20t − 5t² meter efter t sekunder. '
                     'Beräkna h′(1) och förklara vad svaret betyder.', 2)],
         beskrivning='Deriveringsregler, tangentens lutning, extrempunkt och en tillämpning.'),

    # ---- Gymnasiet 1 ----
    dict(fil='gy1-matematik-volym-skala-och-likformighet', arskurs='gy1', amne='Matematik',
         titel='Volym, skala och likformighet', omrade='Matematik 1 / nivå 1: geometri', tid='35 minuter',
         instruktion=['Volym: rätblock b · l · h, cylinder π · r² · h, kon (π · r² · h) / 3, klot (4 · π · r³) / 3. 1 dm³ = 1 liter.',
                      'Skala 1 : n betyder att 1 cm på kartan är n cm i verkligheten.',
                      'Om längdskalan mellan två likformiga figurer är k blir areaskalan k² och volymskalan k³.'],
         uppgifter=[('Beräkna volymen av en cylinder med radien 3 cm och höjden 10 cm. Svara med ett heltal. [] cm³', 1),
                    ('Beräkna volymen av en kon med radien 4 cm och höjden 9 cm. Svara med ett heltal. [] cm³', 1),
                    ('Beräkna volymen av ett klot med radien 6 cm. Svara med ett heltal. [] cm³', 1),
                    ('Ett akvarium är 60 cm långt, 30 cm brett och 40 cm högt. Hur många liter vatten rymmer det? [] liter', 1),
                    ('På en karta i skala 1 : 50 000 är avståndet mellan två orter 8 cm. Hur långt är det i verkligheten? [] km', 1),
                    ('En burk är en cylinder som rymmer 1,0 liter och har diametern 10 cm. Hur hög är burken? Svara med en decimal. [] cm', 2),
                    ('Två likformiga trianglar har motsvarande sidor som är 6 cm och 15 cm. Den mindre har arean 20 cm². '
                     'Hur stor är arean av den större? [] cm²', 2)],
         beskrivning='Volym av cylinder, kon och klot, skala på karta och likformighet med längd-, area- och volymskala.'),

    dict(fil='gy1-matematik-linjara-modeller', arskurs='gy1', amne='Matematik',
         titel='Linjära modeller – jämför tre avtal', omrade='Matematik 1 / nivå 1: samband och förändring', tid='35 minuter',
         instruktion=['Ett linjärt samband har formen y = kx + m. k är förändringen per enhet och m är startvärdet.',
                      'Två linjer skär varandra där y-värdena är lika: sätt de två uttrycken lika med varandra och lös ekvationen.'],
         text=('Tre mobilabonnemang. A: 120 kr i månaden plus 20 kr per GB. B: 300 kr i månaden med obegränsat antal GB. '
               'C: 200 kr i månaden plus 10 kr per GB.'),
         uppgifter=[('Skriv en formel för kostnaden y kr för abonnemang A efter x GB.', 1),
                    ('Vid hur många GB kostar A och B lika mycket? Ställ upp och lös en ekvation. [] GB', 1),
                    ('Vilket abonnemang är billigast vid 15 GB? Visa med en uträkning.', 1),
                    ('Vad betyder talen 20 och 120 i formeln för A?', 1),
                    ('För vilka antal GB är C billigare än A? Lös olikheten.', 1),
                    ('Bestäm k och m för linjen genom punkterna (2, 7) och (6, 19). k = []   m = []', 1),
                    ('Rita graferna för A och B i samma koordinatsystem (x: 0–12 GB, y: 0–400 kr).', 'ruta')],
         beskrivning='Linjära modeller för tre abonnemang: formler, skärningspunkt, olikhet, tolkning av k och m och en graf.'),

    dict(fil='gy1-svenska-retorik', arskurs='gy1', amne='Svenska',
         titel='Retorik – ethos, pathos och logos', omrade='Svenska 1 / nivå 1: tala och övertyga', tid='40 minuter',
         instruktion=['Retorik är konsten att övertyga. Ethos är talarens trovärdighet, pathos är känslor och logos är fakta och logiska argument.',
                      'Mottagare, syfte och situation styr hur man formulerar sig. Talet nedan är ett påhittat exempel.'],
         text=('Kära klasskamrater. Jag har gått i den här skolan i två år, och jag har sett något hända. Förr satt vi i matsalen och '
               'pratade. I dag sitter många med blicken i mobilen. Därför tycker jag att vår skola ska införa mobilfria raster. '
               'Som ordförande i elevrådet har jag pratat med över hundra elever, och de flesta säger att de saknar att umgås på '
               'riktigt. Tänk dig en rast där du hör någons skratt i stället för en notis. Rasten finns för att vi ska vila hjärnan '
               'och träffa varandra. Mobilfria raster är därför inte ett förbud, utan en gåva till oss alla.'),
         uppgifter=[('Vad är talarens tes? Svara med en mening.', 1),
                    ('Ge ett exempel på ethos i talet.', 1),
                    ('Ge ett exempel på pathos i talet.', 1),
                    ('Vilket argument bygger mest på logos? Motivera.', 1),
                    ('Vem är mottagaren och vad är talets syfte?', 1),
                    ('Vilka svagheter har talet och vad skulle göra det mer övertygande?', 2)],
         beskrivning='Analysera ett påhittat tal med retorikens begrepp ethos, pathos och logos, mottagare, syfte och svagheter.'),

    dict(fil='gy1-engelska-formal-email', arskurs='gy1', amne='Engelska',
         titel='Writing a formal email', omrade='Engelska 5 / nivå 1: skriva', tid='35 minuter',
         instruktion=['A formal email is polite and clear: use full forms (I am, not I\'m), no slang, and state your purpose early.',
                      'Layout: greeting, reason for writing, details, polite closing, name. Useful phrases: I am writing to ..., '
                      'Could you please ..., I look forward to hearing from you.',
                      'I brittisk engelska följer avslutningen av hälsningen: Dear Mr Smith → Yours sincerely. Dear Sir or Madam → Yours faithfully.'],
         uppgifter=[('Skriv om till formell engelska: "Hey! Can u send me the info about the course asap?"', 3),
                    ('Skriv om till en formell avslutning: "Thanks a lot, bye!"', 1),
                    ('Vilken avslutning passar efter "Dear Ms Taylor,"? ___', 0),
                    ('Vilken avslutning passar efter "Dear Sir or Madam,"? ___', 0),
                    ('Vilken mening är mest formell? a) I wanna know the price.  b) I would like to know the price. ___', 0),
                    ('Write a formal email (about 80 words) to a language school. Ask about the price, the start date and accommodation.', 6)],
         beskrivning='Formella mejl på engelska: formulera om, välja avslutning och skriva ett eget mejl till en språkskola.'),

    dict(fil='gy1-no-kemi-mol-och-substansmangd', arskurs='gy1', amne='NO / Fysik / Kemi / Biologi', chip='Kemi',
         titel='Mol och substansmängd', omrade='Kemi 1: kvantitativ kemi', tid='40 minuter',
         instruktion=['Substansmängd n mäts i mol: n = m / M, där m är massan i gram och M molmassan i g/mol. Koncentration c = n / V (mol/dm³).',
                      'Molmassor (g/mol): H 1,0   C 12,0   O 16,0   Na 23,0   Cl 35,5   Ca 40,1. Avogadros konstant: 6,02 · 10²³ per mol.'],
         uppgifter=[('Beräkna molmassan för vatten, H₂O. [] g/mol', 0),
                    ('Hur många mol är 36 g vatten? [] mol', 0),
                    ('Beräkna massan av 0,50 mol natriumklorid, NaCl. [] g', 1),
                    ('Beräkna molmassan för kalciumkarbonat, CaCO₃. [] g/mol', 1),
                    ('Hur många gram väger 3,0 mol koldioxid, CO₂? [] g', 1),
                    ('Du löser 0,50 mol natriumhydroxid i vatten till 2,0 dm³ lösning. Beräkna koncentrationen. [] mol/dm³', 1),
                    ('Hur många mol finns i 250 cm³ lösning med koncentrationen 0,20 mol/dm³? [] mol', 1),
                    ('Hur många molekyler finns i 0,50 mol av ett ämne? Svara med tiopotens. []', 1),
                    ('Vätgas förbränns: 2 H₂ + O₂ → 2 H₂O. Hur många mol vatten bildas av 4,0 mol H₂, och hur många mol O₂ går åt? '
                     '[] mol H₂O och [] mol O₂', 1)],
         beskrivning='Mol, molmassa och koncentration: räkna med substansmängd, antal partiklar och reaktionsformler.'),

    dict(fil='gy1-programmering-listor-och-funktioner', arskurs='gy1', amne='Programmering',
         titel='Python: listor, funktioner och loopar', omrade='Programmering 1', tid='40 minuter',
         instruktion=['En lista samlar värden: tal = [4, 8, 15]. Första elementet har index 0, och len(tal) är antalet element. // ger heltalsdivision och % rest.',
                      'En funktion definieras med def och lämnar tillbaka ett värde med return. En while-loop körs så länge villkoret är sant.',
                      'tal.append(x) lägger till x sist i listan, och s.upper() gör om texten till versaler. for o in orden går igenom listan ett element i taget.'],
         uppgifter=[('Vad skriver programmen ut? a) []   b) []', 0,
                     kodrad(('a)', 'tal = [4, 8, 15]\nprint(tal[1])'),
                            ('b)', 'tal = [2, 4, 6]\ntal.append(8)\nprint(len(tal))'))),
                    ('c) Vad skrivs ut? []   d) Vad skrivs ut? Skriv raderna efter varandra. ___', 0,
                     kodrad(('c)', 'def dubbla(x):\n    return x * 2\nprint(dubbla(5) + 1)'),
                            ('d)', 'orden = ["kal", "ba", "lo"]\nfor o in orden:\n    print(o.upper())'))),
                    ('e) Vad skrivs ut? []   f) Vad skrivs ut? ___', 0,
                     kodrad(('e)', 'x = 10\nwhile x > 3:\n    x = x - 4\nprint(x)'),
                            ('f)', 'a = 7\nb = 2\nprint(a // b, a % b)'))),
                    ('Skriv en funktion kvadrat(x) som lämnar tillbaka x upphöjt till 2.', 1),
                    ('Skriv kod som summerar talen i listan tal = [3, 5, 9] med en for-loop och skriver ut summan.', 2)],
         beskrivning='Läsa och skriva Python med listor, funktioner, while- och for-loopar samt heltalsdivision och rest.'),

    # ---- Gymnasiet 2 ----
    dict(fil='gy2-matematik-exponentialfunktioner', arskurs='gy2', amne='Matematik',
         titel='Exponentialfunktioner och logaritmer', omrade='Matematik 2 / nivå 2', tid='40 minuter',
         instruktion=['En exponentialfunktion har formen y = C · aˣ. C är startvärdet och a är tillväxtfaktorn.',
                      'Logaritmen lg x är det tal man ska upphöja 10 till för att få x: lg 1000 = 3.',
                      'Ekvationen aˣ = b har lösningen x = lg b / lg a. Använd räknare där det behövs.'],
         uppgifter=[('Beräkna 2⁵ = [] och 5⁻² = []', 0),
                    ('Beräkna lg 100 = [] och lg 0,01 = [] utan räknare.', 0),
                    ('Lös 2ˣ = 64 utan räknare. x = []', 0),
                    ('Lös 3ˣ = 20 med räknare. Svara med två decimaler. x = []', 1),
                    ('En bakteriekultur har 500 bakterier och antalet fördubblas varje timme. Skriv en funktion för antalet y efter x timmar.', 1),
                    ('Hur många bakterier finns det efter 6 timmar? []', 0),
                    ('Efter hur lång tid finns det 100 000 bakterier? Svara med två decimaler. [] timmar', 1),
                    ('Ett ämne halveras var 5:e år. Hur stor andel finns kvar efter 15 år? []', 0),
                    ('En bil värd 200 000 kr minskar i värde med 12 % per år. Vad är den värd efter 4 år? Avrunda till hundratal kronor.', 1)],
         beskrivning='Exponentialfunktioner, tillväxtfaktor och logaritmer: lösa exponentialekvationer och tolka tillväxt och avtagande.'),

    dict(fil='gy2-matematik-trigonometri', arskurs='gy2', amne='Matematik',
         titel='Trigonometri – räta och allmänna trianglar', omrade='Matematik 1 och 3: trigonometri', tid='40 minuter',
         instruktion=['I en rätvinklig triangel: sin v = motstående / hypotenusan, cos v = närliggande / hypotenusan, tan v = motstående / närliggande.',
                      'Sinussatsen: a / sin A = b / sin B. Cosinussatsen: a² = b² + c² − 2bc · cos A. Area: T = (b · c · sin A) / 2.',
                      'Ställ in räknaren på grader. Svara med en decimal om inget annat anges.'],
         uppgifter=[('Beräkna längden x. [] cm', 0,
                     triangel(5.736, 8.192, 10, sida_a='x', sida_c='10 cm', vinklar=('35°', '', ''), rattvinkel='C', hojd=110)),
                    ('I en rätvinklig triangel är den närliggande kateten 8 cm och den motstående 6 cm. Beräkna vinkeln v. [] °', 0),
                    ('En stege är 4,0 m lång och bildar vinkeln 70° med marken. Hur högt upp når den? [] m', 0),
                    ('I en triangel är A = 40°, B = 65° och a = 8 cm. Beräkna sidan b. [] cm', 1),
                    ('I en triangel är b = 7 cm, c = 9 cm och vinkeln A = 50° mellan dem. Beräkna sidan a. [] cm', 1),
                    ('Beräkna arean av triangeln i uppgiften ovan. [] cm²', 1),
                    ('Beräkna sin 30° = [] och cos 60° = [] utan räknare.', 0),
                    ('Från en punkt 50 m från ett torn är höjdvinkeln till tornets topp 32°. Hur högt är tornet? [] m', 1)],
         beskrivning='Sinus, cosinus och tangens i räta trianglar samt sinussatsen, cosinussatsen och areaformeln.'),

    dict(fil='gy2-matematik-sannolikhet-och-kombinatorik', arskurs='gy2', amne='Matematik',
         titel='Sannolikhet och kombinatorik', omrade='Matematik: sannolikhet och kombinatorik', tid='40 minuter',
         instruktion=['Sannolikhet = gynnsamma utfall / alla utfall. I ett träddiagram multiplicerar du längs en gren och adderar mellan grenar.',
                      'Utan återläggning ändras sannolikheterna för nästa dragning.',
                      'Antal sätt att ordna n olika saker är n! = n · (n − 1) · ... · 1. Att välja k av n utan hänsyn till ordning kan göras på n! / (k! · (n − k)!) sätt.'],
         uppgifter=[('En påse har 3 röda och 2 blå kulor. Du drar två kulor utan återläggning. Rita ett träddiagram och beräkna sannolikheten för två röda.', 3),
                    ('Beräkna sannolikheten att få en kula av varje färg i uppgiften ovan.', 1),
                    ('Samma påse, men du lägger tillbaka den första kulan innan du drar nästa. Vad är sannolikheten för två röda?', 1),
                    ('Två tärningar kastas. Vad är sannolikheten att summan blir 7?', 1),
                    ('Hur många olika fyrsiffriga koder kan man bilda med siffrorna 0–9 om siffrorna får upprepas? []', 0),
                    ('På hur många sätt kan 5 personer ställa sig i en kö? []', 0),
                    ('Ett lag på 6 personer ska välja 2 till ett uppdrag. På hur många sätt kan det göras? []', 0),
                    ('Vad är sannolikheten att få minst en sexa när man kastar en tärning tre gånger? Tips: använd komplementhändelsen.', 2)],
         beskrivning='Träddiagram med och utan återläggning, tärningskast, permutationer, kombinationer och komplementhändelse.'),

    dict(fil='gy2-svenska-kallkritik', arskurs='gy2', amne='Svenska',
         titel='Källkritik', omrade='Svenska 2: sakprosa och källor', tid='35 minuter',
         instruktion=['Fyra frågor att ställa till en källa: Är den äkta? Är den beroende av andra källor? Är den samtida, det vill säga nära i tid och rum? '
                      'Finns det en tendens, alltså ett syfte eller intresse bakom?',
                      'En primärkälla kommer direkt från händelsen. En sekundärkälla beskriver den i efterhand.'],
         uppgifter=[('Du hittar en blogg där en säljare av kosttillskott skriver att produkten botar trötthet. Vilket källkritiskt kriterium är viktigast? Förklara.', 2),
                    ('Ett inlägg i sociala medier visar en bild "från gårdagens översvämning", men bilden är tre år gammal. Vilket eller vilka kriterier brister? Förklara.', 2),
                    ('Tre tidningar publicerar exakt samma text om en händelse, eftersom alla fått den från samma nyhetsbyrå. Är det tre oberoende källor? Förklara.', 1),
                    ('Förklara skillnaden mellan primärkälla och sekundärkälla. Ge ett exempel på vardera.', 2),
                    ('Hur kan du kontrollera att ett påstående du läst på nätet stämmer? Nämn tre sätt.', 2),
                    ('Skriv en bedömning (3–4 meningar) av en källa som du själv använder när du söker information.', 4)],
         beskrivning='Källkritiska kriterier och begrepp: äkthet, beroende, samtidighet, tendens, primär- och sekundärkälla.'),

    dict(fil='gy2-engelska-analysing-a-short-text', arskurs='gy2', amne='Engelska',
         titel='Analysing a short text', omrade='Engelska 6 / nivå 2: litteratur', tid='40 minuter',
         instruktion=['Read the text carefully. Answer the questions in English, in full sentences.',
                      'Support your answers with short quotes from the text.'],
         text=("The last bus of the night left without her. Mira stood under the flickering streetlamp and watched its red "
               "lights shrink into the dark. She had promised her mother she would be home by ten. Now it was almost "
               "midnight, and her phone was dead. For a moment she wanted to cry. Then she noticed the snow falling quietly "
               "around her, soft as feathers, covering the whole street in white. She tucked her scarf tighter, took a deep "
               "breath, and began to walk. The road was long, but it was hers to walk, and for the first time all week the "
               "silence did not feel empty."),
         uppgifter=[('Describe the setting: time, place and weather.', 1),
                    ('Is the narrator in the first or the third person? How can you tell?', 1),
                    ("How does Mira's mood change during the text? Quote two phrases that show it.", 2),
                    ('What might the flickering streetlamp and the snow symbolise?', 2),
                    ('Explain the last sentence: "the silence did not feel empty".', 2),
                    ('Write a short paragraph (3–4 lines) that continues the story in the same tone.', 3)],
         beskrivning='Analysera en kort original-text på engelska: miljö, berättare, stämning, symbolik och eget fortsatt skrivande.'),

    dict(fil='gy2-fysik-rorelse-och-newtons-lagar', arskurs='gy2', amne='NO / Fysik / Kemi / Biologi', chip='Fysik',
         titel='Rörelse och Newtons lagar', omrade='Fysik 1: mekanik', tid='40 minuter',
         instruktion=['Medelhastighet v = s / t. Likformigt accelererad rörelse: v = v₀ + a · t och s = v₀ · t + a · t² / 2.',
                      'Newtons andra lag: F = m · a. Tyngd: F = m · g, där g = 9,82 m/s². 1 m/s = 3,6 km/h.',
                      'Skriv med lämpligt antal värdesiffror.'],
         uppgifter=[('En bil kör 150 km på 2,0 h. Beräkna medelhastigheten i km/h och i m/s. [] km/h  och  [] m/s', 0),
                    ('Omvandla 90 km/h till m/s. [] m/s', 0),
                    ('En cyklist accelererar från stillastående till 8,0 m/s på 4,0 s. Beräkna accelerationen. [] m/s²', 1),
                    ('Hur lång sträcka tillryggalägger cyklisten under dessa 4,0 s? [] m', 1),
                    ('Vilken kraft krävs för att ge en låda med massan 12 kg accelerationen 1,5 m/s²? Friktionen försummas. [] N', 1),
                    ('Beräkna tyngden av en person med massan 70 kg. [] N', 1),
                    ('En sten släpps från en klippa och faller i 3,0 s. Luftmotståndet försummas. Hur fort rör den sig då? [] m/s', 1),
                    ('Hur högt är klippan i uppgiften ovan? [] m', 1),
                    ('Förklara Newtons första lag med ett exempel från vardagen.', 2)],
         beskrivning='Hastighet, acceleration, Newtons lagar och fritt fall: räkna med v, s, a, F och tyngd.'),

    # ---- Gymnasiet 3 ----
    dict(fil='gy3-matematik-integraler', arskurs='gy3', amne='Matematik',
         titel='Integraler – primitiva funktioner och area', omrade='Matematik 3', tid='40 minuter',
         instruktion=['En primitiv funktion F(x) till f(x) uppfyller F′(x) = f(x). Regeln: ∫ xⁿ dx = xⁿ⁺¹ / (n + 1) + C när n ≠ −1.',
                      'Bestämd integral: ∫ f(x) dx från a till b är F(b) − F(a). Om f(x) ≥ 0 är det arean under kurvan.'],
         uppgifter=[('Bestäm ∫ x⁴ dx.', 1), ('Bestäm ∫ (6x² − 4x + 3) dx.', 1),
                    ('Beräkna ∫ 3x² dx från x = 0 till x = 2. []', 1),
                    ('Beräkna ∫ (2x + 1) dx från x = 1 till x = 4. []', 1),
                    ('Beräkna ∫ 1/x² dx från x = 1 till x = 2. Tips: 1/x² = x⁻². []', 1),
                    ('Beräkna arean mellan kurvan y = x² + 1, x-axeln och linjerna x = 0 och x = 3. []', 1),
                    ('Beräkna arean mellan kurvorna y = x och y = x² mellan deras skärningspunkter.', 2),
                    ('Bestäm funktionen f(x) om f′(x) = 4x − 3 och f(1) = 5.', 2)],
         beskrivning='Primitiva funktioner, bestämda integraler och area mellan kurvor.'),

    dict(fil='gy3-matematik-trigonometriska-ekvationer', arskurs='gy3', amne='Matematik',
         titel='Radianer och trigonometriska ekvationer', omrade='Matematik 4: trigonometri', tid='40 minuter',
         instruktion=['180° = π radianer. På enhetscirkeln är cos v och sin v punktens x- och y-koordinat.',
                      'sin x = a ger x = arcsin a + n · 360° och x = 180° − arcsin a + n · 360°. cos x = a ger x = ± arccos a + n · 360°. '
                      'tan x = a ger x = arctan a + n · 180°.'],
         uppgifter=[('Skriv 60° och 225° i radianer. [] och []', 0),
                    ('Skriv π/6 rad och 3π/2 rad i grader. [] ° och [] °', 0),
                    ('Lös sin x = 0,5 för 0° ≤ x ≤ 360°. x = [] ° eller [] °', 0),
                    ('Lös cos x = −0,5 för 0° ≤ x ≤ 360°. x = [] ° eller [] °', 0),
                    ('Lös tan x = 1 för 0° ≤ x ≤ 360°. x = [] ° eller [] °', 0),
                    ('Lös 2 sin x − 1 = 0 för 0 ≤ x ≤ 2π. Svara exakt i radianer. ___', 1),
                    ('Lös sin x = 0,3 för 0° ≤ x ≤ 360° med räknare. Svara med en decimal. ___', 1),
                    ('Lös cos x = 0,8 allmänt, med en decimal. ___', 1),
                    ('Ange amplitud och period för y = 3 sin 2x. Amplitud: []  Period: [] °', 0)],
         beskrivning='Radianer och enhetscirkeln, lösa trigonometriska ekvationer och läsa av amplitud och period.'),

    dict(fil='gy3-svenska-referat-och-sammanfattning', arskurs='gy3', amne='Svenska',
         titel='Referera, parafrasera och sammanfatta', omrade='Svenska 3 / nivå 3: vetenskapligt skrivande', tid='40 minuter',
         instruktion=['Att citera är att återge ord för ord inom citattecken. Att parafrasera är att återge idén med egna ord. '
                      'Att sammanfatta är att korta ner det viktigaste.',
                      'Ett referat är sakligt: presens, inga egna åsikter, och med hänvisning till källan.'],
         text=['Under sömnen vilar inte hjärnan, den arbetar. Forskning om sömn visar att minnen som skapats under dagen '
               'befästs under natten, särskilt under djupsömnen. Det betyder att den som sover efter att ha pluggat ofta minns '
               'mer än den som är vaken. Under sömnen sorterar hjärnan också bort mindre viktig information och stärker det som verkar '
               'viktigt. Tonåringar behöver i regel åtta till tio timmar sömn per natt, men många sover betydligt mindre, bland '
               'annat eftersom den biologiska klockan under tonåren förskjuts mot senare kvällar. Skolor i flera länder har därför '
               'prövat senare skolstart. Resultaten har varit blandade, men många elever uppger att de känner sig piggare.',
               'Källa: Nextrum, exempeltext om sömn och minne.'],
         uppgifter=[('Vilket är textens huvudbudskap? Svara med en mening.', 1),
                    ('Skriv ett referat av texten på högst 60 ord.', 4),
                    ('Förklara skillnaden mellan att citera, parafrasera och sammanfatta.', 2),
                    ('Vilka påståenden i texten skulle behöva en källa för att vara trovärdiga?', 2),
                    ('Formulera en forskningsfråga som skulle kunna undersöka sambandet mellan sömn och provresultat.', 1)],
         beskrivning='Referera, parafrasera och sammanfatta en saklig text om sömn och minne, och formulera en forskningsfråga.'),

    dict(fil='gy3-engelska-argumentative-essay', arskurs='gy3', amne='Engelska',
         titel='Writing an argumentative essay', omrade='Engelska 6 / nivå 2: skriva', tid='45 minuter',
         instruktion=['A strong argumentative text has a clear thesis, paragraphs that each make one point, a counterargument with a rebuttal, and a conclusion.',
                      'Connectors guide the reader: however (contrast), for example, therefore (result), in addition.'],
         uppgifter=[('Write a thesis statement for the topic "Social media does more harm than good".', 2),
                    ('Match each connector with its function: however, for example, therefore, in addition. '
                     'Functions: adds a point, gives an example, shows contrast, shows a result.', 2),
                    ('Improve this sentence: "Social media is bad because it is bad for people."', 2),
                    ('Write a topic sentence for a paragraph arguing that young people learn useful skills online.', 1),
                    ('Write one counterargument and a rebuttal to it.', 3),
                    ('Write a concluding paragraph of about five lines.', 5)],
         beskrivning='Skriva en argumenterande text på engelska: tes, bindeord, ämnesmening, motargument med bemötande och avslutning.'),

    dict(fil='gy3-so-ekonomi-bnp-inflation-och-riksbanken', arskurs='gy3', amne='SO / Historia / Samhällskunskap', chip='Samhällskunskap',
         titel='Ekonomi: BNP, inflation och Riksbanken', omrade='Samhällskunskap', tid='40 minuter',
         instruktion=['BNP (bruttonationalprodukten) är värdet av alla varor och tjänster som produceras i ett land under ett år.',
                      'Inflation är när priserna i allmänhet stiger. Riksbanken har som mål att inflationen ska vara 2 procent och påverkar den bland annat genom styrräntan.',
                      'Konjunktur är svängningarna i ekonomin: högkonjunktur och lågkonjunktur.'],
         uppgifter=[('Förklara med egna ord vad BNP mäter.', 2),
                    ('En vara kostade 400 kr förra året och kostar 420 kr i år. Hur många procent har priset ökat? [] %', 0),
                    ('Lönen är oförändrad men priserna stiger med 3 procent. Vad händer med köpkraften? ___', 0),
                    ('Lönen ökar nominellt med 3 procent och inflationen är 2 procent. Ungefär hur stor är löneökningen räknat i köpkraft? [] %', 0),
                    ('Vad händer vanligen med inflationen när Riksbanken höjer styrräntan? Förklara kedjan steg för steg.', 2),
                    ('Nämn tre tecken på en lågkonjunktur.', 2),
                    ('Ge ett exempel på en inkomst och ett exempel på en utgift i statens budget.', 1),
                    ('Förklara vad progressiv skatt innebär. Ge ett argument för och ett argument mot.', 2)],
         beskrivning='BNP, inflation, reallön, styrränta, konjunktur och statens budget: begrepp och enkla uträkningar.'),

    dict(fil='gy3-biologi-fran-dna-till-protein', arskurs='gy3', amne='NO / Fysik / Kemi / Biologi', chip='Biologi',
         titel='Från DNA till protein', omrade='Biologi 1: genetik', tid='40 minuter',
         instruktion=['DNA har fyra baser: adenin (A), tymin (T), cytosin (C) och guanin (G). A binder till T och C binder till G.',
                      'Transkription: en gen skrivs av till mRNA i cellkärnan. I RNA ersätts T av U (uracil).',
                      'Translation: ribosomerna läser mRNA tre baser i taget (kodon) och bygger ett protein av aminosyror.',
                      'mRNA bildas komplementärt mot templatsträngen: A ger U, T ger A, C ger G och G ger C.'],
         uppgifter=[('Skriv den komplementära DNA-strängen till TACGGCAT. ___', 0),
                    ('DNA-strängen TACGGCAT är templatsträng. Vilken mRNA-sekvens bildas vid transkriptionen? ___', 0),
                    ('Hur många baser utgör ett kodon, och vad kodar ett kodon för? ___', 0),
                    ('Var i cellen sker translationen? ___', 0),
                    ('En gen har 300 baspar. Hur många aminosyror kodar den för som mest? []', 0),
                    ('Vad är en mutation? Ge ett exempel på en möjlig följd.', 2),
                    ('Förklara skillnaden mellan transkription och translation.', 3),
                    ('Nästan alla celler i kroppen har samma DNA. Varför kan en hudcell och en nervcell ändå se ut och fungera olika?', 2)],
         beskrivning='DNA, basparning, transkription, translation och mutationer: räkna med baser och kodon och förklara genuttryck.'),

    # ---- NP-träning, gymnasiet (2026-10-02) ----
    # Egna uppgifter i samma stil som de nationella proven, aldrig provens egna. Med Gy25 finns prov i
    # matematik nivå 1 och 2, svenska nivå 1 och 3 och engelska nivå 1 och 2.
    dict(fil='gy1-np-matematik-niva-1-utan-digitala-verktyg', arskurs='gy1', amne='Matematik',
         titel='NP-träning: matematik 1 utan räknare', omrade='Nationella provet i matematik nivå 1', tid='40 minuter',
         instruktion=['Nextrums egna uppgifter i samma stil som det nationella provet, inga riktiga provuppgifter.',
                      'Provet har delar utan digitala verktyg, där du skriver svaret eller redovisar kort, och delar med digitala verktyg. Formelbladet får användas på alla delar. Det här bladet är utan digitala verktyg.',
                      'Märket efter uppgiften visar vilken nivå den tränar: E, C eller A.'],
         uppgifter=[('a) 2,4 · 0,5 = []    b) Skriv 0,035 i procentform: [[]] {E}', 0),
                    ('Förenkla (2x + 3) − (x − 4). [[]] {E}', 0),
                    ('Lös ekvationen 3(x − 2) = 12. x = [] {E}', 0),
                    ('Beräkna 10⁻² · 10⁵. [] {E}', 0),
                    ('Bestäm f(−2) om f(x) = 3x² − 1. [] {C}', 0),
                    ('Linjen y = kx + 4 går genom punkten (2, 10). Bestäm k. k = [] {C}', 0),
                    ('Skriv ett förenklat uttryck för arean av en rektangel med sidorna x + 2 och 3x. {C}', 1),
                    ('Summan av tre jämna tal som följer på varandra är 78. Vilka är talen? {C}', 1),
                    ('Ett pris sänks med 20 % och höjs sedan med 20 %. Blir det nya priset högre, lägre eller lika med det första? Motivera. {C}', 2),
                    ('Ett tal ökas med 25 %. Med hur många procent måste det nya talet minskas för att man ska komma tillbaka '
                     'till det ursprungliga? Motivera. {A}', 2)],
         beskrivning='Träning inför nationella provet i matematik nivå 1 utan digitala verktyg: räkning, algebra, funktioner och procent på nivåerna E, C och A.'),

    dict(fil='gy1-np-matematik-niva-1-med-digitala-verktyg', arskurs='gy1', amne='Matematik',
         titel='NP-träning: matematik 1 med räknare', omrade='Nationella provet i matematik nivå 1', tid='45 minuter',
         instruktion=['Nextrums egna uppgifter i samma stil som det nationella provet, inga riktiga provuppgifter.',
                      'Redovisa dina lösningar så att någon annan kan följa dem. Du får använda räknare.',
                      'Märket efter uppgiften visar vilken nivå den tränar: E, C eller A.'],
         uppgifter=[('En bil kostar 285 000 kr och minskar i värde med 14 % per år. Vad är den värd efter 5 år? {E}', 1),
                    ('Ett rätblock har volymen 1,2 dm³ och bottenytan 10 cm × 8 cm. Hur högt är det? {E}', 1),
                    ('Andelen elever som cyklar till en skola ökade från 18 % till 24 %. Hur många procentenheter och hur många procent ökade andelen? {C}', 2),
                    ('Tabellen visar tid och sträcka för en löpare. Är sambandet proportionellt? Bestäm i så fall proportionalitetskonstanten och tolka den. {C}', 2,
                     tabell(['Tid (min)', '5', '10', '20', '30'], [['Sträcka (km)', '1,2', '2,4', '4,8', '7,2']], bredd_kol=90)),
                    ('En klass säljer kakor. De har fasta kostnader på 450 kr, varje kaka kostar 4 kr att baka och säljs för 15 kr. '
                     'Hur många kakor måste de sälja för att gå med vinst? {C}', 2),
                    ('Lös ekvationen 1,05ˣ = 2 grafiskt eller genom att pröva. Tolka svaret om 1,05 är förändringsfaktorn per år för pengar på ett sparkonto. {A}', 2)],
         beskrivning='Träning inför nationella provet i matematik nivå 1 med digitala verktyg: förändringsfaktor, volym, procentenheter, proportionalitet och modellering.'),

    dict(fil='gy1-np-svenska-niva-1-lasforstaelse', arskurs='gy1', amne='Svenska',
         titel='NP-träning: läsförståelse, svenska 1', omrade='Nationella provet i svenska nivå 1', tid='40 minuter',
         instruktion=['Nextrums egna uppgifter i samma stil som det nationella provet, inga riktiga provuppgifter.',
                      'På provets läsdel svarar du på frågor om innehåll, syfte och språk. Stöd svaren på texten.'],
         text=['# Varför lånar svenskan ord?',
               'Svenskan har alltid lånat ord från andra språk. Under medeltiden kom många ord från lågtyskan, eftersom tyska '
               'köpmän i Hansan handlade i svenska städer. Ord som fönster, handla och borgmästare är exempel på sådana lån. På '
               '1700-talet var franskan finkulturens språk, och då kom ord som paraply, byrå och fåtölj. Under 1900-talet och fram '
               'till i dag har engelskan varit den största källan.',
               'Ett lånord brukar anpassas efter svenskan. Det får svensk stavning och böjning, och efter en tid märker de flesta '
               'inte längre att ordet kommer utifrån. Mejl är ett exempel: det kommer från engelskans mail men stavas och böjs som '
               'ett svenskt ord, ett mejl och flera mejl.',
               'Alla är inte lika förtjusta i lånorden. Vissa menar att engelska ord tränger undan svenska, särskilt inom forskning '
               'och näringsliv. Andra ser lånen som ett tecken på att språket lever och förändras. Språkforskare brukar påpeka att '
               'svenskan har tagit emot lån i över tusen år och ändå fortfarande är svenska.'],
         uppgifter=[('Varför kom många lågtyska ord in i svenskan under medeltiden?', 1),
                    ('Vilket språk har gett flest lånord sedan 1900-talet? ___', 0),
                    ('Förklara med egna ord vad som händer med ett lånord när det anpassas till svenskan. Ge ett eget exempel.', 2),
                    ('Ringa in det som bäst beskriver textens syfte:\ninformera om hur svenskan lånar ord – argumentera mot engelska lånord – varna för att svenskan försvinner', 0),
                    ('Vilka två synsätt på engelska lånord beskrivs i texten?', 1),
                    ('Vad menar språkforskarna med att svenskan ”ändå fortfarande är svenska”?', 1)],
         beskrivning='Träning inför nationella provets läsdel i svenska nivå 1: en sakprosatext om lånord med frågor om innehåll, syfte och perspektiv.'),

    dict(fil='gy1-np-svenska-niva-1-skriva', arskurs='gy1', amne='Svenska',
         titel='NP-träning: argumentera, svenska 1', omrade='Nationella provet i svenska nivå 1', tid='50 minuter',
         instruktion=['Nextrums egna uppgifter i samma stil som det nationella provet, inga riktiga provuppgifter.',
                      'På provets skrivdel skriver du utifrån ett texthäfte. Hänvisa till källorna så att läsaren förstår vem som säger vad, '
                      'till exempel ”I en ledare i ... skriver ...”.',
                      'En argumenterande text har en tydlig tes, underbyggda argument, ett bemött motargument och en avslutning.'],
         text=['Underlag: två påhittade källor för övningen.',
               'Källa 1, ur en ledare i en lokaltidning: ”Gratis kollektivtrafik för alla under 20 år skulle ge unga större frihet. '
               'Fler skulle kunna ta sig till jobb, träning och vänner utan att vara beroende av föräldrar med bil.”',
               'Källa 2, ur ett debattinlägg av en kommunpolitiker: ”Ingenting är gratis. Kostar bussen ingenting för unga måste '
               'någon annan betala, genom högre skatt eller sämre turtäthet.”'],
         uppgifter=[('Ämnet är: Ska kollektivtrafiken vara gratis för alla under 20 år? Skriv din tes.', 1),
                    ('Skriv ett argument för din tes som bygger på en av källorna. Hänvisa till källan.', 3),
                    ('Skriv ett motargument och bemöt det.', 3),
                    ('Skriv en avslutning som knyter ihop texten.', 2),
                    ('Skriv hela texten med rubrik på ett eget papper eller på datorn.', 0)],
         beskrivning='Träning inför nationella provets skrivdel i svenska nivå 1: argumenterande text utifrån två källor, med källhänvisning.'),

    dict(fil='gy1-np-engelska-niva-1-reading', arskurs='gy1', amne='Engelska',
         titel='NP-träning: reading, engelska nivå 1', omrade='Nationella provet i engelska nivå 1', tid='40 minuter',
         instruktion=['Nextrums egna uppgifter i samma stil som det nationella provet, inga riktiga provuppgifter.',
                      "In the reading part you answer questions about main ideas, details and the writer's attitude. Use full sentences, except where you are asked for one word."],
         text=['# Science in your back garden',
               'Every winter, hundreds of thousands of people across the UK spend one hour looking out of their windows. They are '
               'not bored; they are doing science. The Big Garden Birdwatch, organised by the bird charity RSPB since 1979, asks '
               'the public to count the birds they see in their gardens or local parks and report the numbers online.',
               'Projects like this are called citizen science: ordinary people collect data that researchers could never gather on '
               'their own. Over the years, the counts have shown worrying trends. House sparrows and starlings, for example, are far '
               'less common than they were when the counts began.',
               'Critics point out that volunteers make mistakes. A beginner might confuse two similar species, and people who enjoy '
               'birds may be more likely to take part when their gardens are full of them. Scientists deal with this by collecting '
               'huge amounts of data and by checking unusual reports. Many participants say that once you start noticing the birds, '
               'you never really stop.'],
         uppgifter=[('What do the participants in the Big Garden Birdwatch do?', 1),
                    ('What trend has the birdwatch shown? Give an example.', 1),
                    ('Name two weaknesses of citizen science mentioned in the text, and how scientists deal with them.', 2),
                    ('Find a word in the text that means "people who work without being paid": ___', 0),
                    ("What is the writer's attitude towards citizen science? Support your answer with the text.", 2)],
         beskrivning='Träning inför nationella provets läsdel i engelska nivå 1: en artikel om medborgarforskning med frågor om huvudtanke, detaljer och attityd.'),

    dict(fil='gy1-np-engelska-niva-1-writing', arskurs='gy1', amne='Engelska',
         titel='NP-träning: writing, engelska nivå 1', omrade='Nationella provet i engelska nivå 1', tid='50 minuter',
         instruktion=['Nextrums egna uppgifter i samma stil som det nationella provet, inga riktiga provuppgifter.',
                      'In the writing part you write a longer text. It is assessed on content, structure and language: how clearly, coherently and accurately you write.',
                      'Useful phrases: In my opinion ..., One reason is ..., On the other hand ..., To sum up ...'],
         uppgifter=[('Topic: "Should all young people do some kind of volunteer work?" Plan your text: your opinion, two or three reasons '
                     'with examples, another point of view and a conclusion.', 3),
                    ('Write your introduction here.', 4),
                    ('Write one body paragraph with a clear topic sentence.', 5),
                    ('Write the rest of the text on a separate sheet of paper or on a computer.', 0)],
         beskrivning='Träning inför nationella provets skrivdel i engelska nivå 1: planera och skriva en argumenterande text om volontärarbete.'),

    dict(fil='gy2-np-matematik-niva-2-utan-digitala-verktyg', arskurs='gy2', amne='Matematik',
         titel='NP-träning: matematik 2 utan räknare', omrade='Nationella provet i matematik nivå 2', tid='40 minuter',
         instruktion=['Nextrums egna uppgifter i samma stil som det nationella provet, inga riktiga provuppgifter.',
                      'Provet har delar utan och med digitala verktyg, och formelbladet får användas på alla delar. Det här bladet är utan digitala verktyg.',
                      'Märket efter uppgiften visar vilken nivå den tränar: E, C eller A.'],
         uppgifter=[('Lös ekvationen x² − 9 = 0. x = [[]] {E}', 0),
                    ('Utveckla (x + 5)². {E}', 1),
                    ('Faktorisera x² − 6x. [[]] {E}', 0),
                    ('Beräkna lg 1000 + lg 0,1. [] {E}', 0),
                    ('Lös ekvationen x² + 2x − 8 = 0. {E}', 1),
                    ('Lös ekvationssystemet y = 2x − 1 och y = −x + 5. {E}', 1),
                    ('För vilka värden på k har ekvationen x² + 4x + k = 0 två reella lösningar? {C}', 2),
                    ('Bestäm symmetrilinjen och minimipunkten för f(x) = x² − 4x + 3. {C}', 2),
                    ('Visa att (n + 1)² − (n − 1)² är delbart med 4 för alla heltal n. {A}', 2)],
         beskrivning='Träning inför nationella provet i matematik nivå 2 utan digitala verktyg: andragradsekvationer, kvadreringsregler, logaritmer, ekvationssystem och bevis.'),

    dict(fil='gy2-np-matematik-niva-2-med-digitala-verktyg', arskurs='gy2', amne='Matematik',
         titel='NP-träning: matematik 2 med räknare', omrade='Nationella provet i matematik nivå 2', tid='45 minuter',
         instruktion=['Nextrums egna uppgifter i samma stil som det nationella provet, inga riktiga provuppgifter.',
                      'Redovisa dina lösningar så att någon annan kan följa dem. Du får använda räknare.',
                      'Märket efter uppgiften visar vilken nivå den tränar: E, C eller A.'],
         uppgifter=[('Höjden y meter för en kastad boll efter x sekunder är y = −4,9x² + 12x + 1,5. Hur högt kommer bollen som högst? {C}', 2),
                    ('Efter hur lång tid slår bollen i marken? {C}', 2),
                    ('Lös ekvationen 500 · 1,07ˣ = 1 200. Svara med två decimaler. {E}', 1),
                    ('Tio elever fick poängen 12, 15, 9, 18, 14, 11, 16, 13, 10 och 17 på ett test. Beräkna medelvärdet och '
                     'standardavvikelsen, räknad som för ett stickprov. {E}', 1),
                    ('Förklara skillnaden mellan korrelation och kausalitet med ett eget exempel. {C}', 2),
                    ('En rektangulär hage ska stängslas in längs tre sidor; den fjärde är en vägg. Det finns 60 m stängsel. '
                     'Vilka mått ger största möjliga area? {A}', 3)],
         beskrivning='Träning inför nationella provet i matematik nivå 2 med digitala verktyg: andragradsfunktioner, exponentialekvationer, statistik och optimering.'),

    dict(fil='gy2-np-engelska-niva-2-reading', arskurs='gy2', amne='Engelska',
         titel='NP-träning: reading, engelska nivå 2', omrade='Nationella provet i engelska nivå 2', tid='40 minuter',
         instruktion=['Nextrums egna uppgifter i samma stil som det nationella provet, inga riktiga provuppgifter.',
                      'Show that you understand what the text says and how. Use full sentences, except for one-word answers.'],
         text=['# Tomorrow, I promise',
               'Almost everyone knows the feeling. An essay is due on Friday, and on Thursday evening you find yourself reorganising '
               'your bookshelf or suddenly deciding that your room needs a deep clean. '
               'You are not lazy: you are procrastinating.',
               'For a long time, procrastination was seen as a problem of time management. Many psychologists now describe it differently. Procrastination, they '
               'argue, is mainly about managing feelings. We put off tasks that make us feel bored, anxious or insecure, and reach '
               'for something that makes us feel better right now. The relief is real, but short-lived; the task, and the stress, are still waiting.',
               'This explains why buying a new planner rarely helps. More useful strategies target the feeling itself, for example '
               'breaking a task into tiny steps or starting with just five minutes.',
               'None of this means that every delay is harmful. Letting an idea rest can improve it. The problem begins when putting '
               'things off becomes a habit that costs us sleep, grades or peace of mind.'],
         uppgifter=[('How was procrastination explained in the past, and how do many psychologists explain it now?', 2),
                    ('Why, according to the writer, does buying a new planner rarely help?', 1),
                    ('What does the word "short-lived" mean? ___', 0),
                    ('How does the final paragraph change the perspective of the text?', 2),
                    ('Describe the tone of the first paragraph and give an example that supports your answer.', 1)],
         beskrivning='Träning inför nationella provets läsdel i engelska nivå 2: en essä om att skjuta upp saker, med frågor om innehåll, ton och struktur.'),

    dict(fil='gy2-np-engelska-niva-2-writing', arskurs='gy2', amne='Engelska',
         titel='NP-träning: writing, engelska nivå 2', omrade='Nationella provet i engelska nivå 2', tid='50 minuter',
         instruktion=['Nextrums egna uppgifter i samma stil som det nationella provet, inga riktiga provuppgifter.',
                      'In the writing part you write a longer, well-structured text in which you discuss a topic from more than one angle.',
                      'Useful phrases: It could be argued that ..., A common objection is ..., Nevertheless ..., All things considered ...'],
         uppgifter=[('Topic: "A cashless society: progress or problem?" Plan a text where you discuss advantages and disadvantages '
                     'and give your own opinion.', 3),
                    ('Write your introduction here.', 4),
                    ('Write a paragraph that presents the strongest argument against your own opinion, and respond to it.', 5),
                    ('Write the rest of the text on a separate sheet of paper or on a computer.', 0)],
         beskrivning='Träning inför nationella provets skrivdel i engelska nivå 2: en diskuterande text om ett kontantlöst samhälle.'),

    dict(fil='gy3-np-svenska-niva-3-utredande-text', arskurs='gy3', amne='Svenska',
         titel='NP-träning: utredande text, svenska 3', omrade='Nationella provet i svenska kurs 3 och nivå 3', tid='60 minuter',
         instruktion=['Nextrums egna uppgifter i samma stil som det nationella provet, inga riktiga provuppgifter.',
                      'På provet skriver du en utredande text utifrån ett texthäfte: du ställer en fråga, redogör för olika perspektiv '
                      'med korrekt källhänvisning och drar en egen slutsats.',
                      'Håll isär vad källorna säger och vad du själv tycker.'],
         text=['Underlag: två påhittade källor för övningen.',
               'Källa 1, ur en intervju med en svensklärare: ”Mina elever skriver mer än någon generation före dem: chattar, '
               'kommentarer, inlägg. De växlar hela tiden mellan olika sätt att skriva beroende på mottagare, och det är en färdighet i sig.”',
               'Källa 2, ur en krönika i en dagstidning: ”Korta meddelanden tränar inte förmågan att bygga upp ett långt resonemang. '
               'Jag oroar mig för att unga får allt svårare att skriva sammanhängande texter.”'],
         uppgifter=[('Formulera en frågeställning om hur sociala medier påverkar ungas skrivande.', 1),
                    ('Sammanfatta vad källa 1 säger, med egna ord och med hänvisning till källan.', 2),
                    ('Sammanfatta vad källa 2 säger på samma sätt.', 2),
                    ('Jämför källorna: på vilket sätt är de oense, och kan båda ha rätt?', 2),
                    ('Skriv en slutsats som svarar på din frågeställning.', 3),
                    ('Skriv hela texten med inledning, avhandling och avslutning på ett eget papper eller på datorn.', 0)],
         beskrivning='Träning inför nationella provets skrivdel i svenska nivå 3: utredande text utifrån två källor, med frågeställning, källhänvisning och slutsats.'),
]
