# -*- coding: utf-8 -*-
"""Övningsblad för Högstadiet, åk 7–9. Format och regler: se verktyg/bygg-banken.py."""
from figurer import *  # noqa: F401,F403

BLAD = [
    dict(fil='ak7-matematik-procent', arskurs='ak7', amne='Matematik',
         titel='Procent i vardagen', omrade='Procent', tid='30 minuter',
         instruktion=['Procent betyder hundradelar: 25 % = 25/100 = 0,25.',
                      'För att räkna ut en procentsats av ett tal kan du multiplicera talet med decimalformen.',
                      'Visa hur du räknar.'],
         uppgifter=[('Skriv 40 % i decimalform.', 1), ('Skriv 0,07 i procentform.', 1),
                    ('Hur mycket är 10 % av 350 kr?', 1), ('Hur mycket är 25 % av 80?', 1),
                    ('En tröja kostar 400 kr. Priset sänks med 30 %. Vad kostar tröjan nu?', 2),
                    ('I en klass på 25 elever har 15 elever en cykel. Hur många procent har en cykel?', 2),
                    ('Ett pris höjs från 200 kr till 250 kr. Hur många procent är höjningen?', 2)],
         beskrivning='Procentform och decimalform, procent av ett tal, rabatt och höjning.'),

    dict(fil='ak8-engelska-oregelbundna-verb', arskurs='ak8', amne='Engelska',
         titel='Irregular verbs – past tense', omrade='Oregelbundna verb', tid='25 minuter',
         instruktion=['Oregelbundna verb får inte -ed i dåtid. De måste läras in.',
                      'Skriv verbet i dåtid (past tense). Fyll sedan i meningen.'],
         uppgifter=[('go → ___   Yesterday we ___ to the cinema.', 0),
                    ('eat → ___   She ___ a big breakfast this morning.', 0),
                    ('buy → ___   I ___ a new phone last week.', 0),
                    ('think → ___   We ___ the test was easy.', 0),
                    ('write → ___   He ___ a letter to his grandmother.', 0),
                    ('take → ___   They ___ the bus to school.', 0),
                    ('Skriv tre meningar på engelska om vad du gjorde i helgen. '
                     'Använd minst två oregelbundna verb.', 3)],
         beskrivning='Sex vanliga oregelbundna verb i dåtid, och tre egna meningar.'),

    dict(fil='ak9-matematik-linjara-funktioner', arskurs='ak9', amne='Matematik',
         titel='Linjära funktioner: y = kx + m', omrade='Funktioner', tid='30 minuter',
         instruktion=['I y = kx + m är k lutningen: hur mycket y ökar när x ökar med 1.',
                      'm är värdet där linjen skär y-axeln.',
                      'Visa dina uträkningar.'],
         uppgifter=[('Vad är k och m i y = 3x + 2?', 1),
                    ('Beräkna y när x = 4 i y = 2x − 5.', 1),
                    ('En linje går genom punkterna (0, 1) och (2, 7). Bestäm k.', 2),
                    ('Skriv ekvationen för linjen i uppgiften ovan.', 1),
                    ('En taxi kostar 45 kr i startavgift och 12 kr per kilometer. '
                     'Skriv en formel för priset y kr när man åker x km.', 1),
                    ('Hur långt kan man åka för 225 kr med taxin?', 2),
                    ('Rita linjen y = −x + 3 i ett koordinatsystem.', 'ruta')],
         beskrivning='Lutning och m-värde, linjen genom två punkter, en taxiformel och en graf.'),

    # ---- Åk 7 ----
    dict(fil='ak7-matematik-uttryck-och-ekvationer', arskurs='ak7', amne='Matematik',
         titel='Uttryck och ekvationer', omrade='Algebra', tid='35 minuter',
         instruktion=['En variabel, till exempel x, står för ett tal som kan variera.',
                      'Förenkla genom att lägga ihop likadana termer: 3x + 2x = 5x. Parentes: 2(x + 3) = 2x + 6.',
                      'En ekvation löser du genom att göra samma sak på båda sidor. Kontrollera svaret.'],
         uppgifter=[('Beräkna värdet av 3x + 4 när x = 5.', 1), ('Beräkna värdet av 2a − b när a = 6 och b = 3.', 1),
                    ('Förenkla 4x + 3x.', 0), ('Förenkla 5a + 2 + 3a − 1.', 1), ('Förenkla 3(x + 4).', 1),
                    ('Lös ekvationen 5x − 3 = 22.', 2), ('Lös ekvationen 4x + 7 = 2x + 15.', 2),
                    ('Ett paket kostar p kr. Skriv ett uttryck för vad 4 paket kostar tillsammans med en fraktavgift på 30 kr.', 1),
                    ('Maja är x år och hennes bror är 3 år äldre. Tillsammans är de 25 år. Ställ upp en ekvation och lös den.', 2)],
         beskrivning='Värden av uttryck, förenkling, ekvationer med x på båda sidor och att ställa upp en ekvation ur en text.'),

    dict(fil='ak7-matematik-vinklar-och-trianglar', arskurs='ak7', amne='Matematik',
         titel='Vinklar och trianglar', omrade='Geometri', tid='35 minuter',
         instruktion=['Vinkelsumman i en triangel är 180°. I en fyrhörning är den 360°.',
                      'Sidovinklar, som tillsammans bildar en rät linje, är sammanlagt 180°.',
                      'Arean av en triangel är bas · höjd / 2. En likbent triangel har två lika långa sidor och två lika stora basvinklar.'],
         uppgifter=[('Beräkna vinkel C i triangeln. [] °', 0,
                     triangel(7.43, 9.21, 9.06, vinklar=('48°', '67°', 'C = ?'), hojd=200)),
                    ('I en likbent triangel är toppvinkeln 40°. Hur stor är var och en av basvinklarna? [] °', 0),
                    ('En vinkel är 115°. Hur stor är dess sidovinkel? [] °', 0),
                    ('Hur stor är varje vinkel i en liksidig triangel? [] °', 0),
                    ('En rätvinklig triangel har en vinkel på 35°. Hur stor är den tredje vinkeln? [] °', 0),
                    ('Tre av vinklarna i en fyrhörning är 90°, 100° och 80°. Hur stor är den fjärde? [] °', 0),
                    ('Beräkna arean av en triangel med basen 10 cm och höjden 6 cm. [] cm²', 0),
                    ('Rita en triangel med vinklarna 90°, 45° och 45°. Vad kallas en sådan triangel?', 'ruta')],
         beskrivning='Vinkelsumma, sidovinklar och area: beräkna okända vinklar i trianglar och fyrhörningar.'),

    dict(fil='ak7-svenska-ordklasser', arskurs='ak7', amne='Svenska',
         titel='Ordklasser', omrade='Grammatik', tid='30 minuter',
         instruktion=['Substantiv är namn på saker, djur och människor. Adjektiv beskriver substantiv. Verb är handlingar. '
                      'Adverb beskriver verb och adjektiv (snabbt, mycket).',
                      'Pronomen ersätter substantiv (hon, den, vi). Preposition visar läge (på, under). '
                      'Konjunktion binder ihop (och, men, eftersom). Räkneord är tal.'],
         uppgifter=[('Vilken ordklass är ordet "snabbt" i "Hon springer snabbt"? ___', 0),
                    ('Vilken ordklass är ordet "under" i "Katten sover under bordet"? ___', 0),
                    ('Vilken ordklass är ordet "och" i "Jag gillar äpplen och päron"? ___', 0),
                    ('Vilken ordklass är ordet "hon" i "Hon bor i Solna"? ___', 0),
                    ('Vilken ordklass är ordet "röda" i "Den röda bilen stannade"? ___', 0),
                    ('Vilken ordklass är ordet "tre" i "Jag har tre syskon"? ___', 0),
                    ('Byt ut namnen mot pronomen: Anna gav Erik boken. → ___ gav ___ den.', 0),
                    ('Fyll i en konjunktion som passar: Jag vill gå ut ___ det regnar.', 0),
                    ('Skriv tre prepositioner: ___, ___, ___', 0),
                    ('Skriv en mening som innehåller både ett adverb och ett adjektiv. Skriv vilka orden är.', 2)],
         beskrivning='Känna igen ordklasser i meningar: adverb, preposition, konjunktion, pronomen, adjektiv och räkneord.'),

    dict(fil='ak7-engelska-reading-the-school-trip', arskurs='ak7', amne='Engelska',
         titel='Reading: The school trip', omrade='Läsförståelse', tid='30 minuter',
         instruktion=['Read the text. Then answer the questions in English (except question 8).',
                      'Use your own words when you can.'],
         text=("Last Friday, my class went on a school trip to a farm outside the city. We left school at "
               "eight o'clock and took the bus. It was raining when we arrived, so we all put on our rain "
               "jackets and boots. First, we met the farmer, Mrs Ward. She showed us the cows, the pigs and "
               "a very friendly horse called Max. Then we helped to feed the chickens and collect the eggs. "
               "I found five eggs! After lunch, we made butter from cream. It was hard work, but it tasted "
               "great on fresh bread. On the bus back to school, everyone was tired but happy. I want to go "
               "there again next year."),
         uppgifter=[('Where did the class go? ___', 0), ('What was the weather like when they arrived? ___', 0),
                    ('Who is Mrs Ward? ___', 0), ("What was the horse's name? ___", 0),
                    ('What did they do after lunch?', 1),
                    ('How did the writer feel on the bus home? Why?', 2),
                    ('Find a word in the text that means "glad": ___', 0),
                    ('Översätt till svenska: We helped to feed the chickens.', 1),
                    ('Write three sentences about a trip you have made. Use the past tense.', 3)],
         beskrivning='Läsförståelse på engelska om en skolutflykt till en gård: sju frågor, en översättning och egen skrivuppgift.'),

    dict(fil='ak7-no-cellen', arskurs='ak7', amne='NO / Fysik / Kemi / Biologi', chip='Biologi',
         titel='Cellen – livets minsta enhet', omrade='Biologi: celler', tid='35 minuter',
         instruktion=['Alla levande varelser består av celler. Både djurceller och växtceller har cellkärna, cellmembran, '
                      'cytoplasma och mitokondrier.',
                      'Växtceller har dessutom cellvägg, kloroplaster och en stor vakuol.'],
         uppgifter=[('Fyll i: Cellen är livets ___ enhet.', 0),
                    ('Vilken del av cellen innehåller arvsmassan (DNA)? ___', 0),
                    ('Vilken del omger cellen och bestämmer vad som får komma in och ut? ___', 0),
                    ('Vilka delar finns bara i växtceller? ___', 1),
                    ('Vad sker i kloroplasterna? ___', 0),
                    ('Vad är mitokondriernas uppgift?', 2),
                    ('Skriv fotosyntesen i ord: koldioxid + ___ + ljus → druvsocker + ___', 0),
                    ('Varför kan en växtcell ha en fast form medan en djurcell är mjukare?', 2),
                    ('Rita en djurcell och skriv namnet på tre av delarna.', 'ruta')],
         beskrivning='Cellens delar och deras uppgifter, skillnaden mellan växtceller och djurceller och fotosyntesen.'),

    dict(fil='ak7-so-hur-sverige-styrs', arskurs='ak7', amne='SO / Historia / Samhällskunskap', chip='Samhällskunskap',
         titel='Hur Sverige styrs', omrade='Demokrati och val', tid='30 minuter',
         instruktion=['Sverige är en demokrati: folket bestämmer genom fria val. Val hålls vart fjärde år.',
                      'Riksdagen har 349 ledamöter och stiftar lagar. Regeringen, med statsministern i spetsen, genomför riksdagens beslut.',
                      'Kommunerna ansvarar bland annat för skola och äldreomsorg, och regionerna för sjukvården.'],
         uppgifter=[('Vad betyder ordet demokrati? Förklara med egna ord.', 2),
                    ('Hur ofta är det val till riksdagen? ___', 0),
                    ('Hur många ledamöter har riksdagen? ___', 0),
                    ('Vem leder regeringen? ___', 0),
                    ('Vad är skillnaden mellan riksdagen och regeringen?', 2),
                    ('Nämn två saker som kommunen ansvarar för. ___ och ___', 0),
                    ('Vad är yttrandefrihet? Ge ett exempel.', 2),
                    ('Varför är det viktigt att många röstar i val? Skriv två skäl.', 2)],
         beskrivning='Demokrati och val i Sverige: riksdag, regering, kommun och yttrandefrihet.'),

    dict(fil='ak7-tyska-hallo-och-verben-sein-haben', arskurs='ak7', amne='Moderna språk',
         titel='Tyska: Hallo! Presentera dig', omrade='Presentation, sein och haben', tid='30 minuter',
         instruktion=['Hallo = hej. Ich heiße ... = jag heter ... Ich bin ... Jahre alt = jag är ... år gammal.',
                      'sein (vara): ich bin, du bist, er/sie/es ist, wir sind, ihr seid, sie sind. '
                      'haben (ha): ich habe, du hast, er/sie/es hat, wir haben, ihr habt, sie haben.',
                      'Substantiv skrivs alltid med stor bokstav på tyska och har genus: der, die eller das.'],
         uppgifter=[('Översätt: Jag heter Max. ___', 0), ('Översätt: Jag är tretton år gammal. ___', 0),
                    ('Fyll i sein: Ich ___ Schüler. Du ___ nett. Wir ___ Freunde.', 0),
                    ('Fyll i haben: Ich ___ einen Hund. Sie (hon) ___ zwei Brüder. Wir ___ Hunger.', 0),
                    ('Skriv med bokstäver: 3 = ___, 7 = ___, 10 = ___', 0),
                    ('Vad betyder orden på svenska? Mutter ___, Bruder ___, Hund ___, Schule ___', 0),
                    ('Skriv der, die eller das: ___ Mutter, ___ Hund, ___ Haus, ___ Schule', 0),
                    ('Skriv tre meningar på tyska om dig själv: namn, ålder och var du bor.', 3)],
         beskrivning='Nybörjartyska: presentera sig, verben sein och haben, siffror, familjeord och genus.'),

    # ---- Åk 8 ----
    dict(fil='ak8-matematik-pythagoras-sats', arskurs='ak8', amne='Matematik',
         titel='Pythagoras sats', omrade='Geometri', tid='35 minuter',
         instruktion=['I en rätvinklig triangel gäller a² + b² = c², där c är hypotenusan: den längsta sidan, mitt emot den räta vinkeln.',
                      'a och b kallas kateter. Ta roten ur för att få fram sidans längd.',
                      'Svara med en decimal om svaret inte blir ett heltal.'],
         uppgifter=[('Beräkna hypotenusan i den vänstra triangeln och den okända kateten i den högra. '
                     'Vänster: [] cm   Höger: [] cm', 0,
                     flera(triangel(6, 8, 10, sida_a='6 cm', sida_b='8 cm', sida_c='?', rattvinkel='C', hojd=100),
                           triangel(5, 12, 13, sida_a='5 cm', sida_b='?', sida_c='13 cm', rattvinkel='C', hojd=100))),
                    ('En rektangel är 12 cm lång och 5 cm bred. Hur lång är diagonalen? [] cm', 0),
                    ('En stege är 5,0 m lång. Foten står 1,4 m från en vägg. Hur högt upp på väggen når stegen? [] m', 2),
                    ('Är en triangel med sidorna 7 cm, 24 cm och 25 cm rätvinklig? Motivera med en uträkning.', 2),
                    ('Är en triangel med sidorna 5 cm, 6 cm och 8 cm rätvinklig? Motivera med en uträkning.', 2),
                    ('Beräkna avståndet mellan punkterna (1, 2) och (5, 5). [] längdenheter', 2)],
         beskrivning='Pythagoras sats: räkna ut hypotenusa och katet, diagonaler, stege mot vägg och avstånd mellan punkter.'),

    dict(fil='ak8-matematik-statistik-och-sannolikhet', arskurs='ak8', amne='Matematik',
         titel='Lägesmått och sannolikhet', omrade='Statistik och sannolikhet', tid='35 minuter',
         instruktion=['Medelvärde = summan delat med antalet. Median = det mittersta värdet när de står i ordning. '
                      'Typvärde = det vanligaste värdet. Variationsbredd = största minus minsta.',
                      'Sannolikhet = antal gynnsamma utfall / antal möjliga utfall. Den kan skrivas som bråk, decimaltal eller procent.'],
         uppgifter=[('Fem elever sprang 100 m på 14, 16, 15, 18 och 22 sekunder. Beräkna medelvärdet och medianen. '
                     'Medelvärde: [] s   Median: [] s', 1),
                    ('Vad är variationsbredden i uppgiften ovan? [] s', 0),
                    ('Vad är typvärde och median i 3, 5, 5, 6, 7, 9, 9, 9, 10? Typvärde: []   Median: []', 0),
                    ('Medelvärdet av fyra tal är 8. Tre av talen är 5, 9 och 10. Vilket är det fjärde talet? []', 1),
                    ('I en påse finns 4 röda, 3 blå och 5 gröna kulor. Du drar en kula utan att titta. '
                     'Vad är sannolikheten att den är blå?', 1),
                    ('Vad är sannolikheten att kulan i uppgiften ovan inte är grön?', 1),
                    ('Du kastar en vanlig tärning. Vad är sannolikheten att få ett jämnt tal?', 1),
                    ('Du kastar en tärning två gånger. Vad är sannolikheten att få sexa båda gångerna?', 1)],
         beskrivning='Medelvärde, median, typvärde och variationsbredd samt enkel sannolikhet med kulor och tärning.'),

    dict(fil='ak8-svenska-satsdelar', arskurs='ak8', amne='Svenska',
         titel='Satsdelar: subjekt, predikat och objekt', omrade='Grammatik', tid='30 minuter',
         instruktion=['Predikatet är verbet i satsen. Subjektet är den eller det som gör något: fråga "vem eller vad" + predikatet.',
                      'Objektet är den eller det något görs med: fråga "vem eller vad" + predikatet + subjektet.',
                      'Adverbial berättar när, var eller hur: i går, i parken, snabbt.'],
         uppgifter=[('Vad är predikatet i "Eva läser en bok"? ___', 0),
                    ('Vad är subjektet i "Barnen byggde en koja"? ___', 0),
                    ('Vad är objektet i "Barnen byggde en koja"? ___', 0),
                    ('Vilka adverbial finns i "Vi åker till Göteborg i morgon"? ___ och ___', 0),
                    ('Dela upp meningen i subjekt, predikat, objekt och adverbial: Mamma bakade bullar på söndagen.', 2),
                    ('Rätta ordföljden: I morgon jag ska åka till farmor. ___', 1),
                    ('Vilken del är huvudsats och vilken bisats? Jag stannar hemma eftersom jag är sjuk.', 2),
                    ('Gör om till en fråga: Han har läst boken. ___', 0),
                    ('Skriv en mening med subjekt, predikat, objekt och adverbial. Markera delarna.', 2)],
         beskrivning='Satsdelar: hitta subjekt, predikat, objekt och adverbial, rätta ordföljd och skilja huvudsats från bisats.'),

    dict(fil='ak8-no-atomer-och-grundamnen', arskurs='ak8', amne='NO / Fysik / Kemi / Biologi', chip='Kemi',
         titel='Atomer och grundämnen', omrade='Kemi: atomens byggnad', tid='35 minuter',
         instruktion=['En atom har en kärna med protoner (positiva) och neutroner (utan laddning). Runt kärnan finns elektroner (negativa).',
                      'Antalet protoner bestämmer vilket grundämne det är. En neutral atom har lika många elektroner som protoner.',
                      'Ett grundämne består av en sorts atomer. En kemisk förening består av flera sorters atomer, till exempel H₂O.'],
         uppgifter=[('Vilken laddning har protoner, neutroner och elektroner? ___, ___ och ___', 0),
                    ('Kol har atomnummer 6. Hur många protoner har en kolatom? []', 0),
                    ('En neutral syreatom har 8 protoner. Hur många elektroner har den? []', 0),
                    ('Vad står beteckningarna för? H = ___, O = ___, C = ___, Na = ___', 0),
                    ('Hur många atomer av varje sort finns i en vattenmolekyl, H₂O? ___', 0),
                    ('Hur många atomer finns det sammanlagt i en molekyl koldioxid, CO₂? []', 0),
                    ('Ringa in de grundämnen som står i listan: vatten – syre – järn – salt – guld', 0),
                    ('Vad är skillnaden mellan ett grundämne och en kemisk förening? Ge ett exempel på varje.', 2),
                    ('Rita en modell av en heliumatom: 2 protoner, 2 neutroner och 2 elektroner.', 'ruta')],
         beskrivning='Atomens delar och laddningar, grundämnen och kemiska föreningar samt att läsa kemiska formler.'),

    dict(fil='ak8-so-industrialiseringen', arskurs='ak8', amne='SO / Historia / Samhällskunskap', chip='Historia',
         titel='Industrialiseringen i Sverige', omrade='Historia', tid='35 minuter',
         instruktion=['Läs texten och stryk under det viktigaste.',
                      'Svara sedan på frågorna med egna ord.'],
         text=('Fram till mitten av 1800-talet bodde de flesta svenskar på landsbygden och levde av jordbruk. '
               'Från ungefär 1850 började det som kallas industrialiseringen. Järnvägar byggdes, vilket gjorde '
               'det lättare att transportera varor. Sågverk, järnbruk och textilfabriker växte fram, och '
               'maskiner ersatte handarbete på många ställen. Många flyttade från landet till städerna för att '
               'arbeta i fabrikerna, och det kallas urbanisering. Arbetsdagarna var långa och lönerna låga, och '
               'även barn arbetade. För att få bättre villkor bildade arbetarna fackföreningar. Samtidigt lämnade '
               'mer än en miljon svenskar landet, de flesta för Nordamerika, i hopp om arbete och mark.'),
         uppgifter=[('Ungefär när började industrialiseringen i Sverige? ___', 0),
                    ('Nämn två saker som förändrades i Sverige under industrialiseringen. ___ och ___', 0),
                    ('Vad betyder urbanisering?', 1),
                    ('Varför flyttade många från landsbygden till städerna?', 2),
                    ('Vad är en fackförening och varför bildades de?', 2),
                    ('Varför valde många att emigrera till Nordamerika?', 2),
                    ('Hur skiljer sig ett barns vardag på den tiden från din egen? Skriv tre skillnader.', 2)],
         beskrivning='Läsförståelse om industrialiseringen i Sverige: järnvägar, fabriker, urbanisering, fackföreningar och emigration.'),

    dict(fil='ak8-spanska-presentarse', arskurs='ak8', amne='Moderna språk',
         titel='Spanska: Presentera dig och din familj', omrade='Presentation, ser och tener', tid='30 minuter',
         instruktion=['Hola = hej. Me llamo ... = jag heter ... Tengo ... años = jag är ... år gammal.',
                      'ser (vara): soy, eres, es, somos, sois, son. tener (ha): tengo, tienes, tiene, tenemos, tenéis, tienen.',
                      'Substantiv har genus: el (maskulin) och la (feminin).'],
         uppgifter=[('Översätt: Hej, jag heter Sara. ___', 0), ('Översätt: Jag är tolv år gammal. ___', 0),
                    ('Fyll i ser: Yo ___ sueco. Ella ___ de Madrid. Nosotros ___ amigos.', 0),
                    ('Fyll i tener: Tú ___ un hermano. Mi madre ___ dos gatos. Nosotros ___ una casa.', 0),
                    ('Skriv med bokstäver: 3 = ___, 7 = ___, 10 = ___', 0),
                    ('Vad betyder orden på svenska? madre ___, hermano ___, abuela ___, perro ___', 0),
                    ('Skriv el eller la: ___ casa, ___ libro, ___ escuela, ___ chico', 0),
                    ('Skriv tre meningar på spanska om dig själv: namn, ålder och var du bor.', 3)],
         beskrivning='Nybörjarspanska: presentera sig, verben ser och tener, siffror, familjeord och genus.'),

    # ---- Åk 9 ----
    dict(fil='ak9-matematik-ekvationssystem', arskurs='ak9', amne='Matematik',
         titel='Ekvationssystem', omrade='Algebra', tid='35 minuter',
         instruktion=['Ett ekvationssystem har två ekvationer och två okända tal, x och y.',
                      'Additionsmetoden: addera eller subtrahera ekvationerna så att en variabel försvinner. '
                      'Substitutionsmetoden: lös ut en variabel och sätt in den i den andra ekvationen.',
                      'Kontrollera genom att sätta in lösningen i båda ekvationerna.'],
         uppgifter=[('Lös systemen. a) x + y = 10 och x − y = 4   b) y = 2x och x + y = 12', 2),
                    ('Lös systemen. a) 2x + y = 11 och x + y = 7   b) 3x + 2y = 16 och x − 2y = 0', 2),
                    ('På en bio kostar 2 vuxenbiljetter och 3 barnbiljetter 480 kr. 1 vuxenbiljett och 2 barnbiljetter '
                     'kostar 280 kr. Vad kostar en vuxenbiljett och en barnbiljett?', 3),
                    ('Lös grafiskt: rita linjerna y = x + 1 och y = −x + 5 och läs av skärningspunkten.', 0,
                     koordinatsystem(-1, 6, -1, 6, enhet=40)),
                    ('Hur många lösningar har systemet y = 2x + 3 och y = 2x − 1? Förklara.', 1)],
         beskrivning='Ekvationssystem med additions- och substitutionsmetoden, en textuppgift och en grafisk lösning.'),

    dict(fil='ak9-matematik-forandringsfaktor', arskurs='ak9', amne='Matematik',
         titel='Förändringsfaktor och ränta på ränta', omrade='Procent', tid='35 minuter',
         instruktion=['Förändringsfaktorn visar hur mycket något ändras: en ökning med 20 % ger faktorn 1,20 och en minskning med 15 % ger faktorn 0,85.',
                      'Nytt värde = gammalt värde · förändringsfaktor. Upprepad förändring: gammalt värde · faktor upphöjt till antalet gånger.',
                      'Använd räknare och visa hur du räknat.'],
         uppgifter=[('Vilken förändringsfaktor hör till en ökning med 30 %? [] Och till en minskning med 40 %? []', 0),
                    ('En tröja kostar 600 kr. Priset höjs med 15 %. Vad kostar tröjan sedan?', 1),
                    ('En cykel kostade 3 000 kr och är nu värd 2 400 kr. Hur många procent har värdet minskat?', 1),
                    ('Ett pris ökade från 250 kr till 300 kr. Vilken är förändringsfaktorn och hur många procent är ökningen?', 1),
                    ('Lisa sätter in 5 000 kr på ett konto med 4 % ränta per år. Hur mycket finns på kontot efter 3 år? Avrunda till hela kronor.', 2),
                    ('Befolkningen i en stad är 80 000 och ökar med 2 % per år. Hur många bor där om 2 år?', 2),
                    ('En vara sänks först med 20 % och sedan med 10 %. Hur stor är den sammanlagda minskningen i procent?', 2)],
         beskrivning='Förändringsfaktor, procentuell ökning och minskning, upprepad förändring och ränta på ränta.'),

    dict(fil='ak9-svenska-noveller-och-analys', arskurs='ak9', amne='Svenska',
         titel='Läsa och analysera en novell', omrade='Skönlitteratur', tid='40 minuter',
         instruktion=['Läs novellen två gånger. Skriv svaren med egna ord och stöd dig på texten.',
                      'Begrepp: miljö (var och när), huvudperson, vändpunkt, berättarperspektiv, bildspråk och tema.'],
         text=['Dörren till gympasalen slog igen bakom Noor. Hon höll hårt i väskan och lät blicken glida över klassen. '
               'Alla hade redan hittat sina lag. Hon stod kvar på samma plats som förra veckan och veckan innan.',
               '– Noor, du kan vara med oss! ropade en röst från andra sidan salen.',
               'Hon trodde först att hon hört fel. Det var Alva, hon som alltid hade hela klassen omkring sig. Noor gick sakta '
               'fram, utan att veta om hon skulle le eller inte. Under hela lektionen väntade hon på skämtet, på att någon '
               'skulle skratta åt henne. Men ingenting hände. När Noor till slut gjorde mål ropade Alva högt och räckte upp handen.',
               'På väg ut ur salen kände Noor att väskan var lättare än förut.'],
         uppgifter=[('Var och när utspelar sig novellen? ___', 0),
                    ('Vem är huvudpersonen och hur mår hon i början? Hitta belägg i texten.', 2),
                    ('Vad är novellens vändpunkt?', 1),
                    ('Är berättaren en jag-berättare eller en tredjepersonsberättare? Hur ser du det?', 2),
                    ('Vad menar författaren med att "väskan var lättare än förut"? Tolka bilden.', 2),
                    ('Vilket tema tycker du novellen har? Motivera.', 2)],
         beskrivning='Läsa en kort original-novell och analysera miljö, huvudperson, vändpunkt, berättarperspektiv, bildspråk och tema.'),

    dict(fil='ak9-engelska-present-perfect', arskurs='ak9', amne='Engelska',
         titel='Present perfect eller past simple?', omrade='Grammatik', tid='30 minuter',
         instruktion=['Present perfect (have/has + particip) använder vi när något hänt men tiden inte är viktig, eller när det pågår till nu. '
                      'Signalord: ever, never, already, yet, just, for, since.',
                      'Past simple använder vi när vi säger exakt när det hände: I saw the film last night.'],
         uppgifter=[('Skriv particip: see – saw – ___, go – went – ___, eat – ate – ___, write – wrote – ___', 0),
                    ('Fyll i present perfect: I (visit) ___ London three times.', 0),
                    ('Fyll i present perfect: She (not finish) ___ her homework yet.', 0),
                    ('Fyll i present perfect: ___ you ever (be) ___ to Spain?', 0),
                    ('Fyll i present perfect: They (live) ___ here since 2019.', 0),
                    ('Present perfect eller past simple? I ___ (see) that film last night.', 0),
                    ('Present perfect eller past simple? We ___ (be) friends for ten years.', 0),
                    ('Översätt: Jag har aldrig ätit sushi. ___', 1),
                    ('Skriv tre meningar om saker du har gjort. Använd ever, never eller already.', 3)],
         beskrivning='Present perfect jämfört med past simple: participformer, signalord, fylla i och översätta.'),

    dict(fil='ak9-programmering-python-grunder', arskurs='ak9', amne='Programmering',
         titel='Python: variabler, villkor och loopar', omrade='Programmering', tid='40 minuter',
         instruktion=['En variabel sparar ett värde: x = 5. print(x) skriver ut värdet.',
                      'if och else väljer vad som händer. En for-loop upprepar kod: range(3) ger talen 0, 1 och 2.',
                      'Läs koden rad för rad som om du var datorn.'],
         uppgifter=[('Vad skriver programmen ut? a) []   b) ___', 0,
                     kodrad(('a)', 'x = 4\ny = x * 3\nprint(y)'), ('b)', 'namn = "Alva"\nprint("Hej " + namn)'))),
                    ('Vad skriver programmen ut? c) ___   d) ___ (fyra rader, skriv dem efter varandra)', 0,
                     kodrad(('c)', 'x = 7\nif x > 5:\n    print("stort")\nelse:\n    print("litet")'),
                            ('d)', 'for i in range(4):\n    print(i * 2)'))),
                    ('e) Vad skriver programmet ut? []   f) Vilket fel finns i koden? ___', 0,
                     kodrad(('e)', 'summa = 0\nfor i in range(1, 4):\n    summa = summa + i\nprint(summa)'),
                            ('f)', 'if x = 5:\n    print("fem")'))),
                    ('Skriv ett program som skriver ut talen 1 till 5.', 2),
                    ('Vad är en variabel? Förklara med egna ord.', 2)],
         beskrivning='Läsa och skriva enkel Python: variabler, villkor, for-loopar och felsökning.'),

    dict(fil='ak9-franska-etre-et-avoir', arskurs='ak9', amne='Moderna språk',
         titel='Franska: être och avoir', omrade='Presentation, être och avoir', tid='30 minuter',
         instruktion=["être (vara): je suis, tu es, il/elle est, nous sommes, vous êtes, ils/elles sont. "
                      "avoir (ha): j'ai, tu as, il/elle a, nous avons, vous avez, ils/elles ont.",
                      'Substantiv är maskulina eller feminina: le/un och la/une. Flera heter les.',
                      'På franska säger man att man "har" en viss ålder: j\'ai quinze ans.'],
         uppgifter=[("Översätt: Jag heter Léa. ___", 0), ("Översätt: Jag är femton år gammal. ___", 0),
                    ('Fyll i être: Je ___ suédois. Elle ___ ma sœur. Nous ___ amis.', 0),
                    ('Fyll i avoir: Tu ___ un chat. Il ___ deux frères. Nous ___ faim.', 0),
                    ('Skriv le eller la: ___ maison, ___ livre, ___ table, ___ garçon', 0),
                    ('Skriv med bokstäver: 3 = ___, 7 = ___, 10 = ___', 0),
                    ("Vad betyder orden på svenska? la mère ___, le frère ___, le chien ___, l'école ___", 0),
                    ('Skriv tre meningar på franska om dig själv: namn, ålder och var du bor.', 3)],
         beskrivning='Nybörjarfranska: presentera sig, verben être och avoir, siffror, familjeord och genus.'),

    dict(fil='ak9-so-andra-varldskriget', arskurs='ak9', amne='SO / Historia / Samhällskunskap', chip='Historia',
         titel='Andra världskriget', omrade='Historia', tid='35 minuter',
         instruktion=['Läs texten och stryk under de viktigaste händelserna.',
                      'Svara på frågorna med egna ord.'],
         text=['Andra världskriget började den 1 september 1939 när Tyskland, under Adolf Hitler, anföll Polen. '
               'Storbritannien och Frankrike svarade med att förklara krig mot Tyskland. Under kriget stod de allierade, '
               'till exempel Storbritannien, Sovjetunionen och USA, mot axelmakterna Tyskland, Italien och Japan.',
               'Nazisterna mördade omkring sex miljoner judar i Förintelsen, och miljontals andra människor dödades eller '
               'förföljdes. Kriget i Europa slutade den 8 maj 1945 när Tyskland kapitulerade. Kriget i Asien avslutades '
               'sommaren 1945, efter att USA fällt atombomber över Hiroshima och Nagasaki.',
               'Sverige var neutralt under kriget. Landet hade en svår balansgång mellan Tyskland och de allierade, och tog '
               'emot många flyktingar.'],
         uppgifter=[('Vilket år började andra världskriget, och vilket land anföll Tyskland först?', 1),
                    ('Vilka länder ingick i axelmakterna?', 1),
                    ('Vad kallas mordet på omkring sex miljoner judar?', 1),
                    ('Vad betyder det att ett land är neutralt?', 2),
                    ('Varför var Sveriges situation under kriget svår? Skriv några meningar.', 2),
                    ('Varför är det viktigt att vi fortfarande lär oss om Förintelsen?', 2)],
         beskrivning='Läsförståelse om andra världskriget: början och slut, de båda sidorna, Förintelsen och Sveriges neutralitet.'),
]
