# -*- coding: utf-8 -*-
"""Övningsblad för Lågstadiet, åk 1–3. Format och regler: se verktyg/bygg-banken.py."""
from figurer import *  # noqa: F401,F403

BLAD = [
    dict(fil='ak1-matematik-tiokamrater', arskurs='ak1', amne='Matematik',
         titel='Tiokamrater', omrade='Addition upp till 10', tid='15 minuter',
         instruktion=['Två tal som tillsammans blir 10 kallas tiokamrater.',
                      'Skriv talet som fattas i rutan.',
                      'Rita prickar eller räkna på fingrarna om du vill.'],
         uppgifter=[('7 + [] = 10', 0), ('3 + [] = 10', 0), ('[] + 5 = 10', 0),
                    ('9 + [] = 10', 0), ('[] + 4 = 10', 0), ('2 + [] = 10', 0),
                    ('6 + [] = 10', 0), ('10 = 8 + []', 0),
                    ('Hitta på en egen tiokamrat: [] + [] = 10', 0),
                    ('Rita 10 prickar. Ringa in 4 av dem. Hur många är inte inringade? []', 'ruta')],
         beskrivning='Tio uppgifter om talkamraterna till 10, med rutor att fylla i och en att rita i.'),

    dict(fil='ak2-svenska-stor-bokstav-och-punkt', arskurs='ak2', amne='Svenska',
         titel='Stor bokstav och punkt', omrade='Meningar', tid='20 minuter',
         instruktion=['En mening börjar med stor bokstav och slutar med punkt.',
                      'Namn på personer, djur och platser börjar också med stor bokstav.',
                      'Skriv av meningarna rätt på raden under.'],
         uppgifter=[('idag regnar det i malmö', 1), ('min hund heter bamse', 1),
                    ('vi ska åka till farmor på lördag', 1), ('elsa och omar spelar fotboll', 1),
                    ('jag har en röd cykel', 1),
                    ('Skriv en egen mening om vad du gjorde i helgen.', 2)],
         beskrivning='Skriv av meningar med stor bokstav och punkt, och skriv en egen.'),

    dict(fil='ak3-matematik-multiplikation', arskurs='ak3', amne='Matematik',
         titel='Multiplikation med 2, 5 och 10', omrade='Multiplikationstabellerna', tid='20 minuter',
         instruktion=['Multiplikation är upprepad addition: 3 · 5 betyder 5 + 5 + 5.',
                      'Räkna ut och skriv svaret i rutan.',
                      'På de två sista uppgifterna skriver du hur du tänkte.'],
         uppgifter=[('4 · 2 = []', 0), ('6 · 5 = []', 0), ('3 · 10 = []', 0), ('7 · 2 = []', 0),
                    ('9 · 5 = []', 0), ('8 · 10 = []', 0), ('[] · 5 = 35', 0), ('[] · 2 = 18', 0),
                    ('Ett paket har 5 kakor. Hur många kakor finns det i 6 paket?', 2),
                    ('Lisa har 4 tiokronor. Hur mycket pengar har hon?', 2)],
         beskrivning='Tabellerna 2, 5 och 10, två saknade faktorer och två textuppgifter.'),

    # ---- Åk 1 ----
    dict(fil='ak1-matematik-plus-och-minus-till-20', arskurs='ak1', amne='Matematik',
         titel='Plus och minus upp till 20', omrade='Addition och subtraktion', tid='20 minuter',
         instruktion=['Plus betyder att det blir fler. Minus betyder att det blir färre.',
                      'Räkna ut och skriv svaret i rutan.',
                      'Du får rita prickar eller räkna på fingrarna om du vill.'],
         uppgifter=[('8 + 5 = []', 0), ('9 + 7 = []', 0), ('6 + 6 = []', 0), ('12 + 4 = []', 0),
                    ('15 − 3 = []', 0), ('13 − 6 = []', 0), ('17 − 9 = []', 0), ('20 − 8 = []', 0),
                    ('Mia har 9 äpplen. Hon får 4 till. Hur många äpplen har hon nu? []', 1),
                    ('Det sitter 14 fåglar i ett träd. 5 flyger iväg. Hur många är kvar? []', 1)],
         beskrivning='Addition och subtraktion med tal upp till 20: åtta uppgifter att räkna och två textuppgifter.'),

    dict(fil='ak1-matematik-storre-an-mindre-an-och-talfoljder', arskurs='ak1', amne='Matematik',
         titel='Större än, mindre än och talföljder', omrade='Talens storlek', tid='15 minuter',
         instruktion=['> betyder större än och < betyder mindre än. Den öppna sidan av tecknet vänder sig mot det större talet.',
                      '= betyder lika med.',
                      'Skriv <, > eller = i rutan. Fyll i talen som fattas.'],
         uppgifter=[('12 [] 9', 0), ('5 [] 8', 0), ('6 + 2 [] 8', 0), ('14 [] 17', 0), ('10 [] 7 + 2', 0),
                    ('Fortsätt talföljden: 2, 4, 6, 8, [], []', 0),
                    ('Fortsätt talföljden: 5, 10, 15, 20, [], []', 0),
                    ('Fortsätt talföljden: 20, 18, 16, 14, [], []', 0),
                    ('Vilket tal fattas? 11, 12, [], 14, 15', 0),
                    ('Vilket tal kommer före 30? []', 0), ('Vilket tal kommer efter 49? []', 0)],
         beskrivning='Jämföra tal med <, > och =, fortsätta talföljder och hitta talet före och efter.'),

    dict(fil='ak1-svenska-rimord', arskurs='ak1', amne='Svenska',
         titel='Rimord', omrade='Rim och ljud', tid='15 minuter',
         instruktion=['Ord som låter lika i slutet rimmar. Boll och troll rimmar.',
                      'Läs orden högt, för dig själv eller för en vuxen. Lyssna på hur de slutar.'],
         uppgifter=[('Ringa in ordet som rimmar på mus: hus – bil – ros', 0),
                    ('Ringa in ordet som rimmar på bok: krok – bil – sol', 0),
                    ('Ringa in ordet som rimmar på hatt: kam – katt – hund', 0),
                    ('Ringa in ordet som rimmar på sol: stol – bad – sko', 0),
                    ('Ringa in ordet som rimmar på bil: pil – bit – ben', 0),
                    ('Skriv ett eget ord som rimmar på tak: ___', 0),
                    ('Skriv ett eget ord som rimmar på tåg: ___', 0),
                    ('Rita två saker vars namn rimmar. Skriv orden under bilderna.', 'ruta')],
         beskrivning='Hitta och hitta på rimord: ringa in, skriva egna och rita två saker som rimmar.'),

    dict(fil='ak1-svenska-las-och-svara-mias-hund', arskurs='ak1', amne='Svenska',
         titel='Läs och svara: Mias hund', omrade='Läsförståelse', tid='20 minuter',
         instruktion=['Läs texten. Läs den gärna två gånger.',
                      'Svara på frågorna. Du kan skriva ett ord eller en hel mening.'],
         text=('Mia har en hund. Hunden heter Pelle. Pelle är liten och brun. Han tycker om att leka med '
               'en boll. Varje morgon går Mia och Pelle ut. De går till parken. Där springer Pelle efter '
               'bollen. Sedan dricker han vatten och är trött. Hemma sover Pelle i sin korg.'),
         uppgifter=[('Vad heter hunden?', 1), ('Hur ser Pelle ut?', 1),
                    ('Vad tycker Pelle om att leka med?', 1),
                    ('Vart går Mia och Pelle varje morgon?', 1), ('Var sover Pelle hemma?', 1),
                    ('Rita Pelle i parken.', 'ruta')],
         beskrivning='Läsförståelse om Mia och hennes hund Pelle: fem frågor och en teckning.'),

    dict(fil='ak1-no-arstiderna', arskurs='ak1', amne='NO / Fysik / Kemi / Biologi',
         titel='Årstiderna', omrade='Natur och årstider', tid='15 minuter',
         instruktion=['Året har fyra årstider. De kommer i samma ordning varje år.',
                      'Läs frågorna och skriv svaren. Rita när det står att du ska rita.'],
         uppgifter=[('Skriv årstiderna i rätt ordning: vår, ___, ___, ___', 0),
                    ('Vilken årstid är det när löven ändrar färg och faller av träden? ___', 0),
                    ('Vilken årstid är det när snön ligger på marken? ___', 0),
                    ('Vilken årstid är det när blommorna kommer upp och fåglarna kommer tillbaka? ___', 0),
                    ('Vilka kläder har du på dig en kall vinterdag? Skriv två saker.', 1),
                    ('Vilken årstid tycker du bäst om? Skriv varför.', 2),
                    ('Rita hur det ser ut utomhus på sommaren.', 'ruta')],
         beskrivning='Årstidernas namn och ordning, vad som händer i naturen och egna tankar om årstider.'),

    # ---- Åk 2 ----
    dict(fil='ak2-matematik-tiotal-och-ental', arskurs='ak2', amne='Matematik',
         titel='Tiotal och ental', omrade='Tal upp till 100', tid='20 minuter',
         instruktion=['Ett tal med två siffror har tiotal och ental. I talet 47 är det 4 tiotal och 7 ental.',
                      'Vi kan skriva det så här: 47 = 40 + 7.',
                      'Skriv svaret i rutan.'],
         uppgifter=[('Hur många tiotal och ental är det i 62? [] tiotal och [] ental', 0),
                    ('Hur många tiotal och ental är det i 85? [] tiotal och [] ental', 0),
                    ('34 = [] + 4', 0), ('70 + 9 = []', 0), ('5 tiotal och 3 ental = []', 0),
                    ('Vilket tal är 10 mer än 36? []', 0), ('Vilket tal är 10 mindre än 52? []', 0),
                    ('40 + 30 = []', 0), ('90 − 50 = []', 0),
                    ('Skriv talen i storleksordning, minst först: 48, 84, 38, 83', 1),
                    ('Rita 23 prickar. Ringa in tio prickar åt gången. Hur många tiotal och ental blir det? [] tiotal och [] ental', 'ruta')],
         beskrivning='Tiotal och ental i tal upp till 100: uppdelning, tio mer och tio mindre, och storleksordning.'),

    dict(fil='ak2-matematik-klockan', arskurs='ak2', amne='Matematik',
         titel='Klockan – hel och halv timme', omrade='Klockan', tid='20 minuter',
         instruktion=['Den korta visaren visar timmen. Den långa visaren visar minuterna.',
                      'Pekar den långa visaren på 12 är klockan hel, till exempel tre. '
                      'Pekar den på 6 är klockan halv, till exempel halv fyra.',
                      'Skriv klockslagen med siffror. Tre skrivs 3.00 och halv fyra skrivs 3.30.'],
         uppgifter=[('Vad är klockan? Skriv tiden under varje klocka.', 0,
                     klockor((4, 0), (9, 0), (12, 0))),
                    ('Vad är klockan nu? Skriv tiden under varje klocka.', 0,
                     klockor((2, 30), (8, 30), (11, 30))),
                    ('Rita visarna så att klockan blir sju, och så att den blir halv fem.', 0,
                     klockor(None, None, skrivfalt=False)),
                    ('Klockan är 3.00. Vad är klockan om en timme? [[]]\nVad var klockan för en timme sedan? [[]]', 0),
                    ('Vad gör du klockan 7 på morgonen? Skriv en mening.', 1)],
         beskrivning='Hel och halv timme på analog klocka: läsa av, rita visare och räkna en timme fram och tillbaka.'),

    dict(fil='ak2-matematik-pengar', arskurs='ak2', amne='Matematik',
         titel='Pengar – mynt och sedlar', omrade='Pengar', tid='20 minuter',
         instruktion=['Svenska mynt är 1 kr, 2 kr, 5 kr och 10 kr. Sedlarna är 20 kr, 50 kr, 100 kr och fler.',
                      'Räkna ut och skriv svaret i rutan.'],
         uppgifter=[('5 kr + 2 kr + 1 kr = [] kr', 0), ('10 kr + 10 kr + 5 kr = [] kr', 0),
                    ('20 kr + 5 kr + 5 kr = [] kr', 0),
                    ('Du har 3 tvåkronor och 1 femkrona. Hur mycket pengar har du? [] kr', 0),
                    ('Du betalar en bulle som kostar 7 kr med en tiokrona. Hur mycket får du tillbaka? [] kr', 0),
                    ('En glass kostar 15 kr. Du betalar med 20 kr. Hur mycket får du tillbaka? [] kr', 0),
                    ('En penna kostar 8 kr och ett suddgummi kostar 6 kr. Vad kostar de tillsammans? [] kr', 0),
                    ('Du har 50 kr och köper en bok för 30 kr. Hur mycket har du kvar? [] kr', 0),
                    ('Skriv två olika sätt att betala exakt 10 kr med mynt.', 2),
                    ('Rita mynt som tillsammans blir 12 kr.', 'ruta')],
         beskrivning='Svenska mynt och sedlar: räkna ihop, betala och räkna ut växel.'),

    dict(fil='ak2-svenska-substantiv-och-verb', arskurs='ak2', amne='Svenska',
         titel='Ord för saker och ord för det man gör', omrade='Substantiv och verb', tid='20 minuter',
         instruktion=['Substantiv är ord för saker, djur, människor och platser: stol, hund, Lisa, skola.',
                      'Verb är ord för det man gör: springer, äter, sover.'],
         uppgifter=[('Stryk under substantiven: Hunden sitter på mattan.', 0),
                    ('Ringa in verbet: Pojken kastar bollen.', 0),
                    ('Skriv S för substantiv eller V för verb i rutan: cykel [], hoppar [], bord [], skrattar []', 0),
                    ('Skriv tre substantiv som du ser i klassrummet.', 1),
                    ('Skriv tre verb som du gör på rasten.', 1),
                    ('Fyll i ett verb som passar: Katten ___ mjölk.', 0),
                    ('Skriv en mening med ordet cykel.', 2),
                    ('Skriv en mening med ordet springer.', 2)],
         beskrivning='Skilja substantiv från verb: stryka under, ringa in, sortera och skriva egna meningar.'),

    dict(fil='ak2-no-vaxtens-delar', arskurs='ak2', amne='NO / Fysik / Kemi / Biologi',
         titel='Växtens delar', omrade='Växter', tid='20 minuter',
         instruktion=['Rötterna håller fast växten och tar upp vatten ur jorden.',
                      'Stjälken bär upp växten. Bladen fångar solens ljus. Blomman gör frön.'],
         uppgifter=[('Vilken del av växten tar upp vatten ur jorden? ___', 0),
                    ('Vilken del av växten bär upp den? ___', 0),
                    ('Vilken del av växten gör frön? ___', 0),
                    ('Vad behöver en växt för att kunna växa? Skriv tre saker.', 2),
                    ('Skriv en sak som vi människor får av växter.', 1),
                    ('Vad tror du händer med en blomma som aldrig får vatten?', 2),
                    ('Rita en växt. Skriv namnen på roten, stjälken, bladet och blomman.', 'ruta')],
         beskrivning='Växtens delar och vad var och en gör, vad växter behöver och en teckning att namnge.'),

    # ---- Åk 3 ----
    dict(fil='ak3-matematik-addition-och-subtraktion-med-vaxling', arskurs='ak3', amne='Matematik',
         titel='Addition och subtraktion med växling', omrade='Tal upp till 1 000', tid='25 minuter',
         instruktion=['Ställ upp talen under varandra: ental under ental och tiotal under tiotal.',
                      'Börja räkna längst till höger. Kom ihåg att växla när det behövs.',
                      'Skriv svaret i rutan. Räcker inte raden till uppställningen, använd ett rutat papper.'],
         uppgifter=[('46 + 38 = [[]]', 1), ('127 + 85 = [[]]', 1), ('264 + 359 = [[]]', 1),
                    ('73 − 28 = [[]]', 1), ('152 − 67 = [[]]', 1), ('400 − 143 = [[]]', 1),
                    ('Det finns 235 böcker i skolbiblioteket. Det kommer 118 nya böcker. '
                     'Hur många böcker finns det nu?', 2),
                    ('Farmor har 500 kr. Hon köper en jacka för 285 kr. Hur mycket har hon kvar?', 2)],
         beskrivning='Skriftliga räknemetoder med växling i tal upp till 1 000: sex uppgifter och två textuppgifter.'),

    dict(fil='ak3-matematik-division-dela-lika', arskurs='ak3', amne='Matematik',
         titel='Division – dela lika', omrade='Division', tid='20 minuter',
         instruktion=['Division betyder att dela lika. 12 delat med 3 är 4, för 4 + 4 + 4 = 12.',
                      'Multiplikationstabellerna hjälper dig: 3 · 4 = 12 betyder att 12 : 3 = 4.',
                      'Räkna ut och skriv svaret i rutan.'],
         uppgifter=[('10 : 2 = []', 0), ('15 : 5 = []', 0), ('20 : 4 = []', 0), ('18 : 3 = []', 0),
                    ('30 : 10 = []', 0), ('16 : 2 = []', 0),
                    ('12 kex delas lika mellan 4 barn. Hur många kex får varje barn? [] kex', 1),
                    ('20 elever delas in i grupper med 5 elever i varje. Hur många grupper blir det? []', 1),
                    ('Skriv en multiplikation som hör ihop med 21 : 3 = 7.', 1),
                    ('Hitta på en egen berättelse som passar till 8 : 2 = 4.', 2)],
         beskrivning='Division som att dela lika, och sambandet med multiplikation: sex uppgifter, två textuppgifter och en egen berättelse.'),

    dict(fil='ak3-matematik-langd-och-mat', arskurs='ak3', amne='Matematik',
         titel='Längd – cm, dm och m', omrade='Mäta och jämföra längd', tid='20 minuter',
         instruktion=['Längd mäter vi i millimeter (mm), centimeter (cm), decimeter (dm) och meter (m).',
                      '1 cm = 10 mm, 1 dm = 10 cm och 1 m = 10 dm = 100 cm.',
                      'Skriv svaret i rutan eller på raden. Skriv enheten när den inte står utskriven.'],
         uppgifter=[('1 m = [[]] cm', 0), ('3 dm = [[]] cm', 0), ('2 m = [[]] dm', 0), ('50 cm = [[]] dm', 0),
                    ('Ringa in det som är mest rimligt: En penna är 15 cm – 15 dm – 15 m lång.', 0),
                    ('Ringa in det som är mest rimligt: En dörr är 2 cm – 2 dm – 2 m hög.', 0),
                    ('Ordna från kortast till längst: 1 m, 15 cm, 2 dm, 1 cm', 1),
                    ('Sam är 128 cm lång och Eli är 135 cm lång. Hur mycket längre är Eli?', 1),
                    ('Ett rep är 3 m långt. Du klipper av 85 cm. Hur långt är repet nu? Svara i cm.', 2),
                    ('Spreta med fingrarna. Mät med en linjal från tummen till lillfingret: ___ cm', 0)],
         beskrivning='Enheterna mm, cm, dm och m: växla mellan dem, uppskatta längder och räkna med dem.'),

    dict(fil='ak3-svenska-skriv-en-berattelse', arskurs='ak3', amne='Svenska',
         titel='Skriv en berättelse', omrade='Skriva berättande text', tid='30 minuter',
         instruktion=['En berättelse har en början, en mitt och ett slut.',
                      'I början berättar du vem det handlar om och var det händer. I mitten händer något spännande '
                      'eller roligt. I slutet löser sig det som hänt.',
                      'Börja varje mening med stor bokstav och sluta med punkt.'],
         uppgifter=[('Planera: Vem handlar berättelsen om? Var händer det?', 2),
                    ('Början: Skriv 2–3 meningar. Du kan börja med "En dag hittade ..."', 3),
                    ('Mitten: Vad händer? Något spännande eller roligt.', 3),
                    ('Slutet: Hur slutar det?', 2),
                    ('Hitta på en rubrik till berättelsen.', 1)],
         beskrivning='Planera och skriva en berättelse med början, mitten och slut.'),

    dict(fil='ak3-engelska-colours-and-numbers', arskurs='ak3', amne='Engelska',
         titel='Colours and numbers', omrade='Färger och tal', tid='15 minuter',
         instruktion=['Skriv på engelska.',
                      'Räkna på engelska: one, two, three ... ten.'],
         uppgifter=[('röd = ___', 0), ('blå = ___', 0), ('gul = ___', 0), ('grön = ___', 0),
                    ('Skriv talet med siffror: seven = [], ten = [], four = []', 0),
                    ('Skriv med bokstäver: 3 = ___, 5 = ___, 8 = ___', 0),
                    ('Fyll i orden som fattas: one, two, ___, four, five, ___', 0),
                    ('The sun is ___. (Vilken färg är solen?)', 0),
                    ('Grass is ___. (Vilken färg har gräs?)', 0),
                    ('My favourite colour is ___.', 0)],
         beskrivning='Färger och siffror på engelska: översätta, skriva siffror med bokstäver och fylla i meningar.'),
]
