# -*- coding: utf-8 -*-
"""Övningsblad för Mellanstadiet, åk 4–6. Format och regler: se verktyg/bygg-banken.py."""
from figurer import *  # noqa: F401,F403

BLAD = [
    dict(fil='ak4-engelska-veckodagar-och-manader', arskurs='ak4', amne='Engelska',
         titel='Days of the week and months', omrade='Veckodagar och månader', tid='15 minuter',
         instruktion=['Skriv på engelska.',
                      'Veckodagar och månader börjar alltid med stor bokstav på engelska: Monday, May.'],
         uppgifter=[('måndag = ___', 0), ('onsdag = ___', 0), ('fredag = ___', 0),
                    ('söndag = ___', 0), ('Vilken dag kommer efter Tuesday? ___', 0),
                    ('Vilken månad kommer före May? ___', 0),
                    ('Skriv månaden du fyller år på engelska: ___', 0),
                    ('Fyll i: Today is ___. Tomorrow is ___.', 0)],
         beskrivning='Veckodagar och månader på engelska, åtta korta uppgifter.'),

    dict(fil='ak5-matematik-brak', arskurs='ak5', amne='Matematik',
         titel='Bråk – en del av en helhet', omrade='Bråk', tid='25 minuter',
         instruktion=['Ett bråk visar en del av något.',
                      'Nämnaren, talet under strecket, visar hur många lika stora delar helheten har.',
                      'Täljaren, talet över strecket, visar hur många av delarna vi menar.'],
         uppgifter=[('En pizza är delad i 8 lika stora bitar. Du äter 3. Hur stor del av pizzan åt du?', 1),
                    ('Vilket är störst, 1/2 eller 1/4? Förklara hur du vet.', 2),
                    ('Skriv 2/4 på ett enklare sätt.', 1),
                    ('Hur mycket är 1/3 av 12?', 1),
                    ('Hur mycket är 3/4 av 20?', 1),
                    ('Sortera från minst till störst: 3/5, 1/5, 5/5, 2/5', 1),
                    ('Rita en rektangel och färglägg 2/3 av den.', 'ruta')],
         beskrivning='Bråk som del av en helhet: jämföra, förenkla, räkna ut en del av ett tal.'),

    dict(fil='ak6-no-igelkotten-gar-i-ide', arskurs='ak6', amne='NO / Fysik / Kemi / Biologi',
         titel='Igelkotten går i ide', omrade='Djur på vintern', tid='25 minuter',
         instruktion=['Läs texten två gånger. Stryk under det du tycker är viktigast.',
                      'Svara sedan på frågorna med egna ord.'],
         text=('Igelkotten är ett av de däggdjur i Sverige som går i ide. När hösten kommer äter '
               'den mycket för att bygga upp ett lager av fett. Sedan bygger den ett bo av löv och '
               'gräs, gärna under en buske eller i en komposthög. Där sover den ungefär från '
               'november till april. Under vintern sjunker kroppstemperaturen och hjärtat slår '
               'mycket långsammare än vanligt. Då går det åt lite energi. Om igelkotten väcks för '
               'tidigt gör den av med för mycket av sitt fett och kan få svårt att klara resten av '
               'vintern. Därför ska man inte flytta på lövhögar i trädgården på vintern.'),
         uppgifter=[('Vad betyder det att ett djur går i ide? Förklara med egna ord.', 2),
                    ('Varför äter igelkotten så mycket på hösten?', 2),
                    ('Var bygger igelkotten sitt bo?', 1),
                    ('Vad händer med igelkottens kropp under vintern?', 2),
                    ('Varför ska man inte flytta på lövhögar på vintern?', 2)],
         beskrivning='Läsförståelse om hur igelkotten klarar vintern, fem frågor.'),

    # ---- Åk 4 ----
    dict(fil='ak4-matematik-multiplikationstabellerna', arskurs='ak4', amne='Matematik',
         titel='Multiplikationstabellerna 3 till 9', omrade='Multiplikation och division', tid='25 minuter',
         instruktion=['Tabellerna lär du dig bäst genom att öva lite varje dag.',
                      'Ett knep för 9:an: 9 · 4 är 10 · 4 minus 4.',
                      'Division är multiplikation baklänges: 6 · 7 = 42 ger 42 : 6 = 7.'],
         uppgifter=[('3 · 7 = []', 0), ('4 · 8 = []', 0), ('6 · 6 = []', 0), ('7 · 8 = []', 0),
                    ('9 · 6 = []', 0), ('8 · 9 = []', 0),
                    ('[] · 7 = 42', 0), ('8 · [] = 72', 0), ('[] · 4 = 28', 0),
                    ('54 : 6 = []', 0), ('63 : 7 = []', 0), ('48 : 8 = []', 0),
                    ('En ask innehåller 6 ägg. Hur många ägg är det i 7 askar?', 1),
                    ('48 elever delas in i lag med 6 elever i varje lag. Hur många lag blir det?', 1)],
         beskrivning='Multiplikationstabellerna 3 till 9: räkna, hitta saknad faktor, dela och lösa två textuppgifter.'),

    dict(fil='ak4-matematik-tiondelar-och-decimaltal', arskurs='ak4', amne='Matematik',
         titel='Tiondelar och decimaltal', omrade='Decimaltal', tid='25 minuter',
         instruktion=['Siffran närmast efter kommatecknet visar tiondelar: 0,3 betyder 3/10.',
                      'En decimeter är en tiondels meter, så 3 dm = 0,3 m.',
                      'Skriv svaret i rutan.'],
         uppgifter=[('Skriv 7/10 som decimaltal: []', 0), ('Skriv 0,9 som bråk: []/10', 0),
                    ('Vilket tal är störst, 0,6 eller 0,4? []', 0),
                    ('Vilka decimaltal visar A och B på tallinjen? A = [], B = []', 0,
                     tallinje(0, 2, markerade=[(0.3, 'A'), (1.4, 'B')], delar=10, bredd=840)),
                    ('Sortera med det minsta först: 0,5; 2,1; 1,9; 0,8', 1),
                    ('3,4 + 2,5 = []', 0), ('1,5 + 0,7 = []', 0), ('7,8 − 3,2 = []', 0), ('4,0 − 1,6 = []', 0),
                    ('Ett paket mjöl väger 1,5 kg. Hur mycket väger två paket? [] kg', 0),
                    ('En stege är 2,4 m hög. Hur många decimeter är det? [] dm', 0)],
         beskrivning='Tiondelar och decimaltal: läsa på tallinje, jämföra, addera och subtrahera.'),

    dict(fil='ak4-svenska-synonymer-och-motsatser', arskurs='ak4', amne='Svenska',
         titel='Synonymer och motsatser', omrade='Ordförråd', tid='20 minuter',
         instruktion=['Synonymer är ord som betyder ungefär samma sak: glad och lycklig.',
                      'Motsatsord betyder tvärtom: varm och kall.',
                      'Ett ord kan bilda ett nytt ord tillsammans med ett annat: skola + bok = skolbok.'],
         uppgifter=[('Skriv ett synonym till rolig: ___', 0), ('Skriv ett synonym till snabb: ___', 0),
                    ('Skriv ett synonym till arg: ___', 0), ('Skriv ett synonym till vacker: ___', 0),
                    ('Skriv motsatsen: varm ___, tung ___, ung ___, mörk ___', 0),
                    ('Skriv motsatsen: öppna ___, vinna ___, komma ___, glömma ___', 0),
                    ('Ringa in synonymen till trött: utvilad – sömnig – pigg', 0),
                    ('Sätt ihop orden till ett nytt ord: snö + boll = ___, tand + borste = ___, regn + jacka = ___', 0),
                    ('Dela upp orden i de ord de består av:\nskolgård = ___ + ___   cykelhjälm = ___ + ___', 0),
                    ('Skriv en mening där du använder ett ord och dess motsats.', 2)],
         beskrivning='Synonymer, motsatsord och sammansatta ord: hitta, sortera och bilda egna.'),

    dict(fil='ak4-engelska-describing-people', arskurs='ak4', amne='Engelska',
         titel='Describing people', omrade='Beskriva människor', tid='25 minuter',
         instruktion=['Så beskriver du någon på engelska: She has long hair. He is tall. They have blue eyes.',
                      'Till I, you, we och they säger vi have. Till he, she och it säger vi has.',
                      'I am, you are, he is, she is, we are, they are.'],
         uppgifter=[('Översätt: Hon har långt hår.', 1), ('Översätt: Han är lång.', 1),
                    ('Översätt: Jag har blå ögon.', 1),
                    ('Fyll i has eller have:\nMy sister ___ brown hair.\nWe ___ a big dog.', 0),
                    ('Fyll i am, is eller are:\nI ___ nine.\nShe ___ my friend.\nWe ___ in class four.', 0),
                    ('Vad betyder orden på svenska?\ntall ___   short ___\ncurly ___   young ___', 0),
                    ('Skriv tre meningar om en kompis utan att skriva namnet. Börja med: He/She has ...', 3)],
         beskrivning='Beskriva utseende på engelska med have/has och am/is/are, och skriva om en kompis.'),

    dict(fil='ak4-so-karta-och-vaderstreck', arskurs='ak4', amne='SO / Historia / Samhällskunskap',
         titel='Karta och väderstreck', omrade='Geografi', tid='25 minuter',
         instruktion=['En karta visar hur marken ser ut uppifrån. Det som kartan visar förklaras i teckenförklaringen.',
                      'Väderstrecken är norr, öster, söder och väster. På de flesta kartor är norr uppåt.',
                      'Mellanväderstrecken är nordost, sydost, sydväst och nordväst.'],
         uppgifter=[('Skriv vad bokstäverna betyder: N = ___, Ö = ___, S = ___, V = ___', 0,
                     kompassros(givna=('N', 'Ö', 'S', 'V'), storlek=80)),
                    ('Vilket väderstreck är mitt emot norr? ___', 0),
                    ('Vilket väderstreck ligger mellan söder och väster? ___', 0),
                    ('Solen går upp i ___ och går ner i ___.', 0),
                    ('Är Malmö norr eller söder om Stockholm? ___', 0),
                    ('Vilka två länder har Sverige landgräns till? ___ och ___', 0),
                    ('Vad är en teckenförklaring?', 1),
                    ('Rita en karta över vägen från ditt hem till skolan. Rita en teckenförklaring.', 'ruta')],
         beskrivning='Väderstreck och kartor: kompassen, väderstreck i Sverige, grannländer och en egen karta.'),

    # ---- Åk 5 ----
    dict(fil='ak5-matematik-area-och-omkrets', arskurs='ak5', amne='Matematik',
         titel='Area och omkrets', omrade='Geometri', tid='30 minuter',
         instruktion=['Omkretsen är längden runt en figur: lägg ihop alla sidor.',
                      'Arean är hur stor yta figuren täcker. För en rektangel är arean basen gånger höjden.',
                      'Area mäts i kvadratcentimeter (cm²) eller kvadratmeter (m²).'],
         uppgifter=[('Beräkna rektangelns omkrets och area. Omkrets: [] cm  Area: [] cm²', 0,
                     rektangel('8 cm', '5 cm', b=320, h=200)),
                    ('Ett kvadratiskt bord har sidan 6 dm. Hur lång är bordets omkrets? [] dm', 0),
                    ('En kvadrat har arean 49 cm². Hur lång är en sida? [] cm', 0),
                    ('En rektangel har omkretsen 20 cm och den ena sidan är 6 cm. Hur lång är den andra sidan? [] cm', 0),
                    ('En rektangel har arean 36 cm² och den ena sidan är 9 cm. Hur lång är den andra sidan? [] cm', 0),
                    ('Ett rum är 4 m brett och 5 m långt. Hur många kvadratmeter är golvet? [] m²', 0),
                    ('Rita två olika rektanglar som båda har arean 12 cm². Skriv sidornas längder. En ruta är 1 cm.', 'ruta')],
         beskrivning='Omkrets och area av rektanglar och kvadrater: räkna, räkna baklänges och rita.'),

    dict(fil='ak5-matematik-diagram-och-medelvarde', arskurs='ak5', amne='Matematik',
         titel='Diagram och medelvärde', omrade='Statistik', tid='30 minuter',
         instruktion=['Ett stapeldiagram visar hur många som valt varje alternativ. Läs av höjden på staplarna.',
                      'Medelvärde: lägg ihop alla värden och dela med hur många de är.',
                      'Typvärde är det värde som förekommer oftast. Median är det mittersta värdet när de står i ordning.'],
         uppgifter=[('Diagrammet visar vilket husdjur eleverna i klassen har. Alla har valt ett alternativ. '
                     'Hur många elever har katt? []', 0,
                     stapeldiagram([('Hund', 7), ('Katt', 10), ('Kanin', 3), ('Fågel', 2), ('Inget', 8)],
                                   12, 2, 'Antal elever', hojd=170, bredd=560)),
                    ('Hur många elever har hund eller kanin? []', 0),
                    ('Hur många elever går i klassen? []', 0),
                    ('Fem elever fick 6, 8, 5, 9 och 7 poäng på ett prov. Beräkna medelvärdet. []', 1),
                    ('Vilket är typvärdet i 2, 3, 3, 4, 3, 6, 4? []', 0),
                    ('Vilken är medianen i 4, 9, 2, 7, 5? Ordna talen först. []', 1),
                    ('Rita ett stapeldiagram som visar frukten i en fruktkorg: äpple 5, banan 3, apelsin 4, päron 2.', 'ruta')],
         beskrivning='Läsa av ett stapeldiagram, räkna medelvärde, typvärde och median, och rita ett eget diagram.'),

    dict(fil='ak5-svenska-skriva-dialog', arskurs='ak5', amne='Svenska',
         titel='Skriva dialog med talstreck', omrade='Dialog och skiljetecken', tid='30 minuter',
         instruktion=['När någon pratar i en text kan man använda talstreck: – Hej! sa Lena.',
                      'Efter ett fråge- eller utropstecken skrivs "sa Lena" med liten bokstav. '
                      'Slutar repliken med punkt byts den mot komma: – Jag kommer snart, sa mamma.',
                      'Ersätt gärna "sa" med ett mer talande ord: ropade, viskade, svarade.'],
         uppgifter=[('Gör om till dialog med talstreck: Lena frågade Omar vart han skulle. Omar svarade att han skulle till biblioteket.', 3),
                    ('Rätta felet: – Vilken fin dag! Sa Lena.', 1),
                    ('Rätta felet: – Jag vill åka hem. sa Omar.', 1),
                    ('Skriv tre verb som kan ersätta "sa": ___, ___, ___', 0),
                    ('Skriv en dialog med fyra repliker mellan två personer som möts på en busshållplats. Använd talstreck.', 5)],
         beskrivning='Skriva dialog med talstreck och rätt skiljetecken, och ersätta ordet sa med mer talande verb.'),

    dict(fil='ak5-engelska-present-simple', arskurs='ak5', amne='Engelska',
         titel='Present simple – every day', omrade='Vardagsrutiner', tid='25 minuter',
         instruktion=['Present simple använder vi för det vi gör ofta eller varje dag.',
                      'Till he, she och it lägger vi till -s: I play, she plays.',
                      'Vissa verb får -es: go – goes, watch – watches.'],
         uppgifter=[('Fyll i rätt form: I (play) ___ football on Mondays.', 0),
                    ('Fyll i rätt form: She (play) ___ the piano every day.', 0),
                    ('Fyll i rätt form: He (go) ___ to school by bus.', 0),
                    ('Fyll i rätt form: My dad (watch) ___ the news every evening.', 0),
                    ('Fyll i rätt form: We (eat) ___ lunch at twelve.', 0),
                    ('Fyll i rätt form: They (live) ___ in Stockholm.', 0),
                    ('Översätt: Hon cyklar till skolan varje dag. ___', 1),
                    ('Skriv tre meningar om en vanlig skoldag. Börja med: I wake up at ...', 3)],
         beskrivning='Present simple med -s och -es: fylla i rätt form, översätta och skriva om en vanlig dag.'),

    dict(fil='ak5-so-vikingatiden', arskurs='ak5', amne='SO / Historia / Samhällskunskap',
         titel='Vikingatiden', omrade='Historia', tid='30 minuter',
         instruktion=['Läs texten två gånger. Stryk under det som är viktigast.',
                      'Svara sedan på frågorna med egna ord.'],
         text=('Vikingatiden varade ungefär från år 800 till år 1050. Vikingarna bodde i det som i dag är '
               'Sverige, Norge och Danmark. De flesta var bönder och fiskare, men många gav sig också ut på '
               'långa resor. De seglade i smala långskepp som gick bra både på hav och på floder. '
               'Vikingarna handlade med silver, pälsar och slavar, och en del plundrade också kloster och '
               'städer. Vikingar från Sverige reste ofta österut, genom det som i dag är Ryssland och Ukraina och vidare mot Konstantinopel. '
               'De trodde på många gudar, till exempel Oden, Tor och Frej. Viktiga frågor avgjordes på tinget, '
               'där fria människor samlades. För att skriva använde vikingarna runor, som ristades i sten och trä.'),
         uppgifter=[('När var vikingatiden ungefär?', 1),
                    ('Vad kallades de smala skeppen som vikingarna seglade i?', 1),
                    ('Nämn två saker som vikingarna handlade med.', 1),
                    ('Skriv namnen på två av vikingarnas gudar.', 1),
                    ('Vad var tinget?', 2),
                    ('Varför kan man säga att vikingarna var både bönder och upptäcktsresande? Förklara.', 2)],
         beskrivning='Läsförståelse om vikingatiden: tid, skepp, handel, gudar, tinget och runor.'),

    # ---- Åk 6 ----
    dict(fil='ak6-matematik-negativa-tal-och-koordinatsystem', arskurs='ak6', amne='Matematik',
         titel='Negativa tal och koordinatsystem', omrade='Tal och geometri', tid='30 minuter',
         instruktion=['Negativa tal är tal under noll. På en tallinje ligger de till vänster om noll.',
                      'Ju längre åt vänster ett tal ligger, desto mindre är det.',
                      'I ett koordinatsystem skriver vi (x, y): först x i sidled, sedan y i höjdled.'],
         uppgifter=[('Vilka tal visar punkterna A och B? A = [], B = []', 0,
                     tallinje(-6, 6, markerade=[(-4, 'A'), (3, 'B')], bredd=840)),
                    ('Vilket tal är störst, −3 eller −8? []', 0),
                    ('Sortera med det minsta först: 2, −5, 0, −1, 4', 1),
                    ('Temperaturen är −4 °C och stiger 9 grader. Hur varmt är det då? [] °C', 0),
                    ('Temperaturen är 3 °C och sjunker 7 grader. Hur varmt är det då? [] °C', 0),
                    ('Beräkna 5 − 8 = [] och −2 + 6 = []', 0),
                    ('Vilka koordinater har punkterna? A = ([], []), B = ([], []), C = ([], []), D = ([], [])', 0,
                     koordinatsystem(-5, 5, -4, 4, punkter=[(3, 2, 'A'), (-2, 3, 'B'), (-4, -1, 'C'), (2, -3, 'D')], enhet=32)),
                    ('Rita in punkten E (−3, −2) och punkten F (0, 4) i koordinatsystemet ovan.', 0)],
         beskrivning='Negativa tal på tallinje, i temperaturer och i uträkningar, och koordinater i ett koordinatsystem.'),

    dict(fil='ak6-matematik-enkla-ekvationer', arskurs='ak6', amne='Matematik',
         titel='Enkla ekvationer', omrade='Algebra', tid='30 minuter',
         instruktion=['I en ekvation är ett tal okänt. Vi kallar det ofta x.',
                      'Lös ekvationen genom att göra samma sak på båda sidor. Exempel: x + 5 = 12 ger x = 12 − 5 = 7.',
                      'Kontrollera alltid genom att sätta in svaret.'],
         uppgifter=[('Lös x + 7 = 15. Svar: x = []', 1), ('Lös x − 4 = 9. Svar: x = []', 1), ('Lös 3x = 21. Svar: x = []', 1),
                    ('Lös x : 4 = 6. Svar: x = []', 1), ('Lös 2x + 3 = 11. Svar: x = []', 1), ('Lös 5x − 5 = 20. Svar: x = []', 1),
                    ('Jag tänker på ett tal. Jag multiplicerar det med 4 och lägger till 3. Resultatet blir 31. '
                     'Vilket tal tänkte jag på?', 2),
                    ('En bok kostar x kr. Tre likadana böcker kostar 270 kr. Skriv en ekvation och lös den.', 2),
                    ('Kontrollera din lösning till 2x + 3 = 11 genom att sätta in x i ekvationen.', 1)],
         beskrivning='Enkla ekvationer med en obekant: lösa, kontrollera och ställa upp ur en text.'),

    dict(fil='ak6-svenska-argumenterande-text', arskurs='ak6', amne='Svenska',
         titel='Argumenterande text', omrade='Tycka och motivera', tid='35 minuter',
         instruktion=['I en argumenterande text vill du övertyga läsaren. Du säger vad du tycker och ger skäl, argument.',
                      'En bra text har en tes (din åsikt), två eller tre argument och en avslutning där du upprepar din åsikt.',
                      'Använd ord som eftersom, därför, dessutom och men.'],
         uppgifter=[('Vad är en tes? Förklara med egna ord.', 2),
                    ('Påstående: "Alla elever borde ha längre rast." Skriv två argument som stöder det.', 3),
                    ('Skriv ett motargument, ett skäl som någon skulle kunna ha mot påståendet i uppgiften ovan.', 2),
                    ('Fyll i orden eftersom och dessutom: Jag tycker att vi ska ha gympa varje dag ___ det är bra för kroppen. '
                     '___ blir man piggare på lektionerna.', 0),
                    ('Skriv en kort argumenterande text: "Ska skolan ha läxor?" Börja med din tes.', 6)],
         beskrivning='Argumenterande text: tes, argument och motargument, bindeord och en egen kort text.'),

    dict(fil='ak6-engelska-past-simple', arskurs='ak6', amne='Engelska',
         titel='Past simple – regular verbs', omrade='Dåtid', tid='25 minuter',
         instruktion=['Past simple använder vi för det som hänt och är slut: Yesterday I played football.',
                      'De flesta verb får -ed: play – played. Slutar verbet på -e läggs bara -d till: live – lived.',
                      'Slutar verbet på konsonant + y blir y till -ied: study – studied.'],
         uppgifter=[('Skriv dåtid: walk → ___, play → ___, watch → ___, clean → ___', 0),
                    ('Skriv dåtid: live → ___, like → ___, dance → ___', 0),
                    ('Skriv dåtid: study → ___, try → ___, carry → ___', 0),
                    ('Fyll i dåtid: Yesterday I (play) ___ football with my friends.', 0),
                    ('Fyll i dåtid: Last weekend we (visit) ___ our grandparents.', 0),
                    ('Fyll i dåtid: She (study) ___ for the test on Sunday.', 0),
                    ('Fyll i dåtid: The children (watch) ___ a film last night.', 0),
                    ('Översätt: Vi städade vårt rum i lördags. ___', 1),
                    ('Skriv tre meningar om vad du gjorde i går. Börja med: Yesterday I ...', 3)],
         beskrivning='Past simple med regelbundna verb: böja, fylla i, översätta och skriva om i går.'),

    dict(fil='ak6-no-krafter-i-vardagen', arskurs='ak6', amne='NO / Fysik / Kemi / Biologi',
         titel='Krafter i vardagen', omrade='Fysik: krafter', tid='30 minuter',
         instruktion=['En kraft kan få något att börja röra sig, stanna, ändra riktning eller ändra form. Krafter mäter vi i newton (N).',
                      'Gravitationen drar alla saker mot jorden. Friktion är en kraft som bromsar när två ytor gnuggar mot varandra.'],
         uppgifter=[('Vilken kraft gör att ett äpple faller till marken? ___', 0),
                    ('Vilken kraft bromsar cykeln när du trycker på bromsen? ___', 0),
                    ('Vad mäter vi krafter i? ___', 0),
                    ('Nämn tre saker en kraft kan göra med ett föremål.', 2),
                    ('Varför är det lättare att gå på torr asfalt än på blank is? Förklara.', 2),
                    ('Ge ett exempel där friktion är bra och ett där den är besvärlig.', 2),
                    ('Rita en låda som skjuts över ett golv. Rita pilar som visar gravitationen och friktionen och skriv vad de heter.', 'ruta')],
         beskrivning='Krafter i vardagen: gravitation, friktion och newton, med frågor och en teckning med kraftpilar.'),
]
